#+TITLE: \Huge\vspace{-1em}Variable compleja
#+DATE:
#+SETUPFILE: ../Plantillas/Plantilla.org
#+OPTIONS: toc:nil ;; Nos quitamos el Índice del medio
#+OPTIONS: num:nil
#+LATEX: \vspace{-8em}

* Los números complejos
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT

\defi{1.1} Un número complejo es una expresión \( a + bi \) donde 
\( a,b \in \mathbb{R} \) y \( i \) es la unidad imaginaria, fruto de resolver la
ecuación \( x^2 + 1 = 0 \) en \( \mathbb{R} \). Así, definimos \( i = \sqrt{-1}
\). Si \( z \in \mathbb{C} = a + bi \), \( a = \text{Re }z \) y \( b = \text{Im
}z \) son la parte *real* e *imaginaria* de \( z \).

\defi{1.2} La *suma* y *multiplicación* están definidas en los complejos así:
\[ \left(x_{1}+y_{1} i\right)+\left(x_{2}+y_{2}
i\right)=\left(x_{1}+x_{2}\right)+\left(y_{1}+y_{2}\right) i \]
$$
\left(x_{1}+y_{1} i\right)\left(x_{2}+y_{2} i\right)=\left(x_{1} x_{2}-y_{1} y_{2}\right)+\left(x_{1} y_{2}+x_{2} y_{1}\right) i
$$
Y con estas operaciones \( (\mathbb{C}, +, \cdot) \) es un cuerpo, con \(
0_{\mathbb{C}} = 0 + 0i \) y \( 1_\mathbb{C} = 1 + 0i \).

\defi{1.3} Dado un complejo \( z = x + yi \), llamamos *conjugado* de \( z \), \(
\overline{z} \) a \( x - yi \).

\propo{1.3.1} Se verifica que \( \overline{z_{1}+z_{2}}=\overline{z_{1}}+\overline{z_{2}} \) 
y \( \overline{z_{1} z_{2}}=\overline{z_{1}} \cdot \overline{z_{2}} \).

\defi{1.4.1} Se denomina *módulo* de un complejo \( z = x + yi \), \( |z| \) a \(
\sqrt{x^2 + y^2} \). Se cumple que \( |z| = \sqrt{z\overline{z}} \). 
El módulo cumple que (1) \( |z| \ge 0 \), (2) \( |z| = 0 \iff z = 0 \),
(3) \( |z_1z_2| = |z_1||z_2| \) y (4) \( |z_1 + z_2| \le |z_1| + |z_2| \)

#+BEGIN_EXPORT latex
\dem{ (4) \( 
\left|z_{1}+z_{2}\right|^{2}=\left(z_{1}+z_{2}\right)(\overline{z_{1}+z_{2}})=\left(z_{1}+z_{2}\right
)(\overline{z_{1}}+\overline{z_{2}}) 
=z_{1} \overline{z_{1}}+z_{1} \overline{z_{2}}+z_{2} \overline{z_{1}}+z_{2} \overline{z_{2}} 
=z_{1} \overline{z_{1}}+z_{1} \overline{z_{2}}+\overline{z_{1} \overline{z_{2}}}+z_{2} \overline{z_{2}} 
=\left|z_{1}\right|^{2}+\left|z_{2}\right|^{2}+2 \operatorname{Re}\left(z_{1} \overline{z_{2}}\right) 
 \leq\left|z_{1}\right|^{2}+\left|z_{2}\right|^{2}+2\left|z_{1}\right|\left|z_{2}\right| 
=\left(\left|z_{1}\right|+\left|z_{2}\right|\right)^{2}
 \)  }
#+END_EXPORT

\defi{1.5} Dado un \( z = a + bi \), aplicando \( u = p + iq = z/|z| \),
entonces \( |u| = 1 = p^2 + q^2 \). El ángulo tal que \( p = \cos \alpha, q =
\sin \alpha \) se denomina *argumento*, \( \arg z \).  Así, \( z \) puede representarse como \( z
= |z|(\cos  \alpha  + i \sin \alpha ) \). Esta forma es la *forma polar*, y
también se representa como \( z = |z|e^{i\alpha} \).x 

El argumento cumple que (1) \( \arg \overline{z} = - \arg z \) y (2) \( \arg
z_1z_2 = \arg z_1 + \arg z_2 \).

\defi{1.7 / 1.8} El espacio topológico \( (\mathbb{C}, \delta_E) \) con distancia
euclídea no es compacto. Sin embargo, si tomamos \( \hat{\mathbb{C}} =
\mathbb{C} \cup \{ \infty \} \) entonces sí es compacto, y lo denominamos *plano
complejo ampliado*. La *esfera de Riemann*, \( \mathbb{S} \), es la representación del conjunto \(
\hat{\mathbb{C}} \) en \( \mathbb{R}^3_{(\xi, \eta, \zeta)} \) en una esfera con
centro \( (0, 0, 1/2) \) con ecuación \( \xi^{2}+\eta^{2}+\zeta^{2}-\zeta=0 \).
#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=5cm]{imagenes/esfera.png}
\end{figure}
#+END_EXPORT
La relación entre la esfera y el plano es 
\[ \xi=\frac{x}{1+x^{2}+y^{2}}, \eta=\frac{y}{1+x^{2}+y^{2}}, \zeta=\frac{x^{2}+y^{2}}{1+x^{2}+y^{2}} \]
La *distancia cordal* entre dos puntos \( z_1,z_2 \) es la distancia euclídea 
entre los puntos \( P_1,P_2 \) de la esfera de la esfera de Riemman.

\( \delta(z_1,z_2) =
 \sqrt{\left(\xi_{1}-\xi_{2}\right)^{2}+\left(\eta_{1}-\eta_{2}\right)^{2}+\left(\zeta_{1}-\zeta_{2}\right)^{2}}
 = \frac{\sqrt{\left(x_{1}-x_{2}\right)^{2}+\left(y_{1}-y_{2}\right)^{2}}}{
\sqrt{\left(1+x_{1}^{2}+y_{1}^{2}\right)\left(1+x_{2}^{2}+y_{2}^{2}\right)}} \)

Para un punto en el infinito, la distancia es \( \delta(z, \infty)=\frac{1}{\sqrt{1+x^{2}+y^{2}}} \)

#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT




* Funciones complejas
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT
\defi{2.0} Una función puede ser de tipo \( f: \mathbb{R} \rightarrow
\mathbb{C} \) (f. compleja de var. real) o 
\( f: \mathbb{C} \rightarrow  \mathbb{C} \) (f. compleja de var. compleja).

\defi{2.1.1} \( f = f(z)\) es *continua* en \( z_0 \in \mathbb{C} \) si para todo \(
\epsilon > 0 \) existe \( \delta > 0 \) tal que si \( |z - z_0| < \delta \)
entonces \( |f(z) - f(z_0)| < \epsilon \). \( f \) es *uniformemente continua* en
\( B \subset \mathbb{C} \) si
dado \( \epsilon > 0 \) existe \( \delta > 0 \) tal que para todo \( z_0 \in B
\) y para todo \( z \) tal que \( |z-z_0| < \delta \) entonces \( |f(z) -
f(z_0)| < \epsilon \).  Si \( f \) es uniformemente continua es continua, pero
no siempre a la inversa.

\tma{2.1.1} Si \( f_1(z), f_2(z) \) están definidas en \( A \subset \mathbb{C}
\), \( A \) abierto, y son continuas en \( z_0 \in A \), f_1 + f_2 y f_1/f_2 son
continuas en \( z_0 \). Así, los polinomios complejos son continuos.

\defi{2.1.2} Una función \( f(z) \) en \( A \subset \mathbb{S} \) es continua en
\( z_0 \) si para todo \( \epsilon > 0 \)
 existe \( \eta > 0 \) tal que para todo \( z \in A \) donde \( \delta(z, z_0) <
\eta \) entonces \( \delta(f(z_0), f(z)) < \epsilon \).

\defi{2.2.1, 2.2.2} Una función \( f(z) \) es *derivable* en \( z_0 \) si existe el
límite \( \lim_{z \to z_0} \frac{f(z) - f(z_0)}{z-z_0} \) y es finito.
Si \( z_0 = \infty \), consideramos \( g(z) = f(1/z) \) y \( f \) es derivable
en \( \infty \) si \( g \) es derivable en \( z=0 \).
Una función \( f:A \subset \mathbb{C} \rightarrow  \mathbb{C} \) derivable en todo
\( A \) se llama función *holomorfa* o *analítica.*

\propo{2.3.2} Si \( f \) es derivable en un punto, también es continua en ese
punto.

\propo{2.3.4 (Regla de la cadena)} Sean \( g:A \rightarrow  \mathbb{C} \) y \(
f: B \rightarrow \mathbb{C} \) tales que \( g(A) \subset B \). Si \( g \) es
derivable en \( z_0 \) y \( f\) es derivable en \( g(z_0)  \) entonces \( f
\circ g'(z_0) = f'(g(z_0))g'(z_0) \).

\defi{2.4.1} Una función \( f: A \rightarrow  \mathbb{C} \) es conforme en \(
z_0 \) si existe exsite \( \theta \in [0, 2\pi] \) tal que cualquier curva \(
\gamma(t) \) diferenciable en \( t_0 \), \( \gamma(t_0) = z_0 \) y \(
\gamma'(t_0) \neq 0 \) se transforma por \( f \) en una curva \( \sigma(t) =
f(\gamma(t)) \) diferenciable en \( t_0 \) tal que \( \sigma'(t_0) =
\gamma'(t_0) + \theta \). Si \( \alpha \) es el ángulo en el punto de cruce \(
z_0 \) entre \( \gamma_1, \gamma_2 \), entonces el ángulo de \( f(\gamma_1),
f(\gamma_2) \) es \( \alpha \).  

\tma{2.4.1} Si \( f \) es derivable en \( z_0 \) y \( f'(z_0) \neq 0 \) entonces
\( f \) es conforme en \( z_0 \) y \( \theta = \arg f'(z_0) \). Si \( f \) es
holomorfa, es conforme.
 #+BEGIN_EXPORT latex
\dem{ Por la regla de la cadena, \( \sigma'(t_0) = f'(\gamma(t_0))\cdot \gamma'(t_0) \)  y \( \arg  \sigma'(t_0)
 = \arg f'(\gamma(t_0))+\arg  \gamma'(t_0) \) }
#+END_EXPORT

\defi{2.5.1} Una función de variable compleja puede transformarse a una función
\( f: \mathbb{R}^2 \rightarrow  \mathbb{R}^2 \): \( f(x,y) = (u(x,y) + v(x,y)) =
u(x,y) + v(x,y)i \)

\tma{2.5.1 (Ecuaciones de Cauchy-Riemman) } Sea \( f \). \( f'(z_0) \) existe sii \( f \) es diferenciable como
función de dos variables y las funciones \( u(x,y), v(x,y) \) satisfacen
\vspace{-1em} \[
\frac{\partial u}{\partial x} = \frac{\partial v}{\partial y}, 
\frac{\partial u}{\partial y} = - \frac{\partial v}{\partial x} \]
#+BEGIN_EXPORT latex
\dem{ Suponemos \( f \) derivable en \( z_0 \) complejo, con derivada \( \lambda = f'(z_0) \). 
Si tomamos la aplicación lineal \( l_c : \mathbb{C} \rightarrow  \mathbb{C}; \eta \rightarrow \lambda\eta \).
Entonces \( \lim_{\eta \to 0} \left|\frac{f(z_0 + \eta) - f(z_0)}{\eta} - \lambda  \right| = \lim_{\eta \to 0} 
\frac{|f(z_0 + \eta) - f(z_0) - l_c(\eta)|}{|\eta|} =  0 \). Escribiendo \( f(z_0) \) y 
\( l_c(\eta) \) como componentes reales: (1) \( f(z_0) = u(x_0, y_0) + v(x_0,y_0)i = 
(u(x_0, y_0), v(x_0, y_0)) \) su jacobiano es \( D= \begin{bmatrix}
\frac{\partial u}{\partial x} &  \frac{\partial u}{\partial y} \\ 
\frac{\partial v}{\partial x} &  \frac{\partial v}{\partial y} \\ 
\end{bmatrix}  \) y (2)
\(l_c(\eta) = \lambda\eta = (\lambda_1 + \lambda_2i)(\eta_1 + \eta_2i) = (\lambda_1\eta_1 - \lambda_2\eta_2, \lambda_1\eta_2 + \lambda_2\eta_1)  \), 
que como aplicación lineal \( \mathbb{R}^2 \rightarrow  \mathbb{R}^2 \) 
es \( A= \begin{bmatrix}
\lambda_1 &  -\lambda_2 \\ 
\lambda_2 &  \lambda_1 \\ 
\end{bmatrix}  \). Como el jacobiano la derivada de \( f \) en los reales, y \( A \) es también la diferencial de 
\( f \) en \( z_0 \), \( D = A \), y se dan las ecuaciones. }
#+END_EXPORT

\tma{2.6.1 (Teorema de la función inversa)} Sea \( f \) analítica con derivada
continua en \( A \). Sea \( z_0 \in A\) tal que \( f'(z_0) \neq 0  \). Entonces,
existen \( U, V \) abiertos tal que \( z_0 \in U \), \( f(z_0) \in V \) y \( f:
U \rightarrow  V \) es biyectiva. Además, \(f^{-1}\) es analítica en \( V \) y para
todo \( z \in U \), \( (f^{-1})'(f(z)) = \frac{1}{f'(z)} \).



#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT

* Series de potencias. Funciones elementales

#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT

\defi{3.0.1} Una *sucesión* de complejos es una aplicación \( \mathbb{N}
\rightarrow  \mathbb{C} \) tal que para cada \( n \in \mathbb{N} \) se le
corresponde \( a_n \in \mathbb{C} \). 

\defi{3.0.2} Una *serie* es una sucesión de complejos \( \{A_n\}_{n \in \mathbb{N} }
\) tal que \( A_n = \sum _{i=0}^{n} a_i\).

\defi{3.0.3} Una sucesión es de *Cauchy* o *fundamental* si dado \( \epsilon > 0 \)
existe \( n_0 \in \mathbb{N} \) tal que para todo \( n_1, n_2 \ge n_0 \), se
tiene que \(|a_{n_1} - a_{n_2}| < \epsilon  \).

\defi{3.0.4} Se dice que \( \{a_n\}_{n \in \mathbb{N}} \) es *convergente* a \( a \)
si dado \( \epsilon > 0 \) existe \( n_0 \in \mathbb{N} \) tal que para todo \(
n \ge n_0 \) se tiene \( |a_n-a| < \epsilon \), y diremos \( \lim_{n \to \infty}
a_n=a\).  Asimismo, \( A_n \) es convergente a \( A \) si \( \lim_{n \to \infty}
A_n = A\).

\defi{3.0.5} Una serie \( A_n \) es absolutamente convergente si la serie \(
\sum |a_n|  \) es convergente.

\tma{3.1.1 (Criterio de la raíz) } Dado \( \sum _{i=1}^{\infty} a_i \), sea \(
\lambda = \lim_{n \to \infty} \text{sup} \sqrt[\leftroot{1}\uproot{1}n]{|a_n|}
\). Si \( \lambda < 1 \) la serie converge y si \( \lambda > 1 \) diverge.

\tma{3.1.2 (Criterio del cociente)} Dado  
\( \sum _{i=1}^{\infty} a_i \) sea \( \beta = \lim_{n \to \infty}
\frac{|a_n|}{|a_{n-1}|} \), si \( \beta < 1 \) la serie converge, y si \( \beta >
1 \) diverge.

\defi{3.2.0} Una *sucesión* *de variable compleja* es una aplicación de tal manera
que a cada \( n \in \mathbb{N} \) le corresponde una función \( f_n: A
\rightarrow  \mathbb{C} \). Representamos la sucesión por \( \{ f_n \}_{n \in
\mathbb{N}} \). Asimismo, una *serie de funciones de variable compleja* es el
resultado de sumar dichas funciones: \( F_n(z) = \sum _{i=1}^{n}f_i\).

\defi{3.2.1} Una sucesión \( \{ f_n \}_{n \in N}  \) converge en \( z_0 \in A \) cuando
converge la sucesión numérica \( \{ f_n(z_0) \}_{n \in \mathbb{N}} \). Diremos
que \( \{ f_n \}_{n \in \mathbb{N}} \) *converge puntualmente* cuando converge
para todo \( z \in A \).

\defi{3.2.2} La serie \( f_0 + \cdots + f_n + \cdots \) converge en un punto \(
z_0 \in A \), \( A \) abierto en \( \mathbb{C} \) si la sucesión \( \{ F_n(z_0) \}_{n
\in \mathbb{N}} \) con \( F_n = f_0 + \cdots + f_n \)
converge. La serie converge puntualmente en \( A  \) si \( \{ F_n \}_{n \in
\mathbb{N}} \) converge puntualmente en \( A \).

\defi{3.2.3} La sucesión de funciones \( \{ f_n \}_{n \in N} \) converge
uniformemente a \( f \) si para todo \( \epsilon > 0 \) existe \( n_0 \in
\mathbb{N} \) tal que \( |f_n(z) - f(z)| < \epsilon \) para todo \( z \in A, n
\ge n_0 \). 

\defi{3.2.4} La serie \( \sum _{n=1}^{\infty} f_n(z) \) converge uniformemente
en \( A \) si la sucesión \( \{ F_n \}_{n \in N} \) converge uniformemente en \(
A \).

\tma{3.2.1 Criterio de la mayorante de Weierstrass)} Una condición suficiente
para que \( \sum _{n=1}^{\infty} f_n \) converja uniformemente en \( A \subset
\mathbb{C} \) es que exista una serie \( \sum _{n=1}^{\infty} a_n \) convergente
tal que \( |f_n(z)| \le a_n \) para todo \( z \) y \( n \in \mathbb{N} \).
En tal caso, \( \sum _{n=1}^{\infty} a_n \) es una mayorante de \( \sum
_{n=1}^{\infty} f_n \). 

\defi{3.3.0} Una *serie de potencias* es una serie de la forma \( \sum
_{n=1}^{\infty} a_n(z - z_0)^n \), con \( z_0, a_n \in \mathbb{C} \) para todo
\( n \). Los \( a_n \) se llaman *coeficientes* de la serie.
Si \( z_0=0 \), es decir, \( \sum _{n=1}^{\infty} a_nz^n \) decimos que la serie
está *centrada en el origen*.

\defi{3.3.1 (Teorema de Cauchy-Hadamard)} Dada la serie \( \sum _{n=1}^{\infty}
a_n(z - z_0)^n \) considerando  \(
\lambda = \lim_{n \to \infty} \text{sup} \sqrt[\leftroot{1}\uproot{1}n]{|a_n|}
\); si llamamos \( R = \frac{1}{\lambda} \), tenemos:
- La serie converge absolutamente en el interior del círculo \( D_R = \{z| |z-z_0| < R \} \) y diverge en el exterior \( \overline{D_R} = \{ z| |z-z_0|> R \} \) 
- La convergencia es uniforme en todo circulo de radio \( 0 \le r < R \) 
\( R \) se llama *radio de convergencia* de la serie. 


\tma{3.3.2} La función definida por la suma de serie de potencias en su círculo
de convergencia es derivable en todo punto de dicho círculo:
\[ \frac{\text{d}}{\text{d}z} \left( \sum _{n=0}^{\infty}a_n(z-z_0)^n \right) = 
\sum _{n=0}^{\infty}na_n(z-z_0)^{n-1} \].

\defi{3.4.1} La función exponencial compleja es \[ e^z = \sum_{n=0}^{\infty}
\frac{z^n}{n!} \].
Su radio de convergencia es \( R = \infty \). Cumple también que \( e^{z_1+z_2}
 = e^{z_1}e^{z_2} \).
El exponente puede reescribirse como \( e^z = e^{x+yi} = e^xe^{iy} = e^x(\cos
y + i \sin y) \)

\defi{3.4.2} La función logaritmo se obtiene desde la exponencial. Escribiendo
\( z = r e^{i\theta} \) tenemos que \( \log z  = \log|r| + i\theta = \log|r| + i
\arg(z) \). Como \( \arg(z) = \theta + 2\pi k \), el logaritmo principal es \(
\theta \in [0, 2\pi] = \text{Arg } z \).

\defi{3.4.3} Las funciones seno y coseno se definen a través de sus series de
potencias con \( R = \infty \):
\[ \sin(z) = \sum _{n=0}^{\infty} (-1)^n \frac{z^{2n+1}}{(2n+1)!}\;,\; 
\cos(z) = \sum _{n=0}^{\infty}(-1)^n \frac{z^{2n}}{(2n)!} \]
La derivación es como con los números reales, y las identidades de Euler son
idénticas:
\[ \cos(z) = \frac{e^{iz} + e^{-iz}}{2} \;,\; \sin(z) = \frac{e^{iz} -
e^{-iz}}{2i} \]
\[ \sinh(z) = \frac{e^z - e^{-z}}{2}\;,\; \cosh(z) = \frac{e^z + e^{-z}}{2} \]

\defi{3.4.4} La función potencial con exponente complejo, \( z^\zeta, \zeta \in
\mathbb{C} \) es \( z^{\zeta} = e^{\zeta \log z} \)

\defi{3.5.1 (Funciones multiformes)}  Una función \( f \) es multiforme cuando
\( w = f(z) \) puede tomar diferentes valores para el mismo \( z \). Por
ejemplo, para \( f = \sqrt{z} \), \( f(2i) = 1+i \) y \( f(2i) = -1-i \). 
Esto se debe a que \( z^{1/2} = e^{\frac{1}{2} \log{z}} =
e^{\frac{1}{2}(\log{|z| + i \arg(z))}} = |z|^{\frac{1}{2}}e^{i \frac{\text{Arg
}z + 2k\pi}{2}}, k = 0,1\).

Observamos que como \( k \) puede tomar dos valores, entonces la función tiene
dos ramas, es decir, \( w_1 = \sqrt{r}e^{i \frac{\theta}{2}}\;,\;w_2 =
-\sqrt{r}e^{-i \frac{\theta}{2}} \).
Por tanto, para completar un ciclo en \( w \) necesitamos completar dos ciclos
en \( z \) (uno por rama). Esto genera una *superficie de Riemann* como la
siguiente figura:

#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=9cm]{imagenes/riemann_sqrt.png}
\end{figure}
#+END_EXPORT

En este caso los ejes \( X \) e \( Y \) representan el plano complejo de \( z
\). El eje \( Z \) representa la parte real de \( f(z) \), y el color representa
la imaginaria. El punto de corte del plano es el caso \( \sqrt{-a}, a \in
\mathbb{R}  = 0 + i \sqrt{a}\). Sin embargo, el corte es un artefacto de la
visualización tridimensional de 4 dimensiones.

Debajo se muestra el ejemplo de \( f = \log{z} \), donde el eje \( X \)
representa el argumento, y el color representa la parte real. 

#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=8cm]{imagenes/riemann_log.png}
\end{figure}
#+END_EXPORT

Vemos que el el plano "cae" de nivel en cada vuelta. Esto es el equivalente a
cada rama del logaritmo.


#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT

* Integración en el campo complejo
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT


\defi{4.0.1} Una curva \( \gamma:[a,b] \rightarrow  \mathbb{C} \) es
*rectificable* cuando presenta una longitud finita.

\defi{4.0.2} Una *partición* de un intervalo es el conjunto \( \Delta = \{ a =
t_0 < t_1 < \cdots < t_n = b \} \). La *norma* de la partición es \( |\Delta| =
\max \{ |t_{k-1} - t_k|, k = 0, 1, \cdots, n-1 \} \). Una partición \( \Delta'
\) es *más fina* que otra partición \( \Delta \) cuando \( \Delta \subset \Delta'
\).

\defi{4.0.3} Dados \( f, \gamma, \Delta \), definimos la suma de
Riemman-Stieljes como \( S(\Delta, f, \gamma) = \sum_{k=0}^{n-1}
f(s_k)[\gamma(t_{k+1}) - \gamma(t_{k})]\), con \( s_k \in [t_k, t_{k+1}] \).
\( f \) es *integrable* Riemman-Stieljes (RS) si existe un complejo \( I  \) tal que 
para cualquier \( \epsilon > 0 \)
existe una partición \( \Delta_{\epsilon} \) tal que para toda \(
\Delta_{\epsilon} \subset \Delta \), \( |S(\Delta, f, \gamma) - I| < \epsilon
\). \( I  \) se denota por \( \int_ { a }^{ b } f \; \text{d}\gamma    \).

\defi{4.0.4} Si \( \gamma(t) = \phi(t) + i \psi(t) \), entonces \( \int_ { a }^{ b } f \;
 \text{d}\gamma 
 = \int_ { a }^{ b } f \; \text{d}\phi + i \int_ { a }^{ b } f \; \text{d}\psi 
 \).

\propo{4.1.1} Sean \( f, \gamma \). Entonces existe la integral RS y 
\( \left|\int_ { a }^{ b } f \; \text{d}\gamma  \right| \le ML(\gamma)  \), 
donde \( M = \max \{ |f(t)|\;|\;t \in [a,b] \} \) y \( L(\gamma) \) es la
longitud de \( \gamma \).
#+BEGIN_EXPORT latex
\dem{ \( |S(\Delta, f, \gamma)|  \leq \sum_{k=0}^{n-1}\left|f\left(s_{k}\right)\right|\left|\gamma\left(t_{k+1}\right)-\gamma\left(t_{k}\right)\right| 
 \leq(\max \{|f(t)|, t \in[a, b]\}) \sum_{k=0}^{n-1}\left|\gamma\left(t_{k+1}\right)-\gamma\left(t_{k}\right)\right| 
 \leq M L(\gamma)\) }
#+END_EXPORT

\propo{4.1.2} Si \( f \) es continua en \( [a, b] \) y \( \gamma \) define un
camino de clase \( C^1 \) entonces la integral RS viene dada por 
\( \int_{a}^{b} f \text{d} \gamma=\int_{a}^{b} f \gamma^{\prime} \text{d} t \)
#+BEGIN_EXPORT latex
\dem{ Como \( \int_ { a }^{ b } f \;
 \text{d}\gamma 
 = \int_ { a }^{ b } f \; \text{d}\phi + i \int_ { a }^{ b } f \; \text{d}\psi   \), vamos a demostrar que 
\( \int_ { a }^{ b } f \; \text{d}\phi = \int_ { a }^{ b } f \phi'\; \text{d}t \).
Por la definición de \( I \) existe para todo \( \epsilon > 0 \) una partición tal que \( 
 \left|\sum_{k=0}^{n-1} f\left(s_{k}\right)\left[\varphi\left(t_{k+1}\right)-\varphi\left(t_{k}\right)\right]-\int_{a}^{b} f d \varphi\right|<\epsilon \) 
Por el teorema del valor intermedio: \( \varphi\left(t_{k+1}\right)-\varphi\left(t_{k}\right)=\varphi^{\prime}\left(s_{k}^{\prime}\right)\left(t_{k+1}-t_{k}\right) \),
luego \(  |\sum_{k=0}^{n-1} f\left(s_{k}^{\prime}\right) \varphi^{\prime}\left(s_{k}^{\prime}\right)\left(t_{k+1}-t_{k}\right)-\int_{a}^{b} f d \varphi|<\epsilon\).
Ahora bien, la expresión de sumatorio puede aplicarse a la integral, de modo que 
\(|\sum_{k=0}^{n-1} f\left(s_{k}^{\prime}\right) \varphi^{\prime}\left(s_{k}^{\prime}\right)\left(t_{k+1}-t_{k}\right)-\int_{a}^{b} f \varphi^{\prime} d t|<\epsilon \).
Por último, si denominamos \( S \) al sumatorio anterior, tenemos que \( |\int_{a}^{b} f \varphi^{\prime} d t - 
\int_{a}^{b} f d \varphi | \le |\int_{a}^{b} f \varphi^{\prime} d t - S| + | S - \int_{a}^{b} f d \varphi | \le 2 \epsilon \). 
Repetimos para \( \int_ { a }^{ b } f \; \text{d}\psi  \) y finalmente 
\(  \int_ { a }^{ b } f \; \text{d}\gamma =  \int_ { a }^{ b } f \; \text{d}\phi + i  \int_ { a }^{ b } f \; \text{d}\psi 
=  \int_ { a }^{ b } f\phi' \; \text{d}t + i  \int_ { a }^{ b } f\psi' \; \text{d}t =  
\int_ { a }^{ b } f\gamma' \; \text{d}t \)}
#+END_EXPORT

\defi{4.2.0} Sean \( f, \gamma \). Se define la *integral de \( f \) a lo largo
de \( \gamma \)*, \( \int_\gamma fdz \) como \( \int_ { a }^{ b } f \circ \gamma
\; \text{d}\gamma  \) y, si \( \gamma \) es \( C^1 \), entonces \( \int_\gamma
fdz = \int_ { a }^{ b } f(\gamma(t))\gamma'(t)  \; \text{d} t    \).
La integral cumple:
- Linealidad: \( \int _\gamma (c_1f_1 + c_2f_2) \; \text{d}z  = c_1 \int _\gamma
  f_1\; \text{d} z + c_2 \int _\gamma f_2 \; \text{d}z    \)
- Si \( -\gamma \) es el camino opuesto a \( \gamma \): \( \int _\gamma f \;
  \text{d}z = - \int _{-\gamma} f \; \text{d}z  \)
- Yuxtaposición: \( \int _{\gamma_1 \cup \gamma_2} f \; \text{d}z = \int
  _{\gamma_1} f \; \text{d}z  + \int _{\gamma_2} f \; \text{d}z  \)
- Se tiene la siguiente stimación: \( |\int _\gamma f \; \text{d}z| \le \int _\gamma |f|| \; \text{d}z|  = \int_ { a
  }^{ b } |f(t)||\gamma'(t)| \; \text{d}t  \le ML(\gamma) \).

\propo{4.2.1} Sea \( \{ f_n \}_{n \in \mathbb{N}} \) una sucesión de funciones,
y \( \gamma \). Si \( f_n \) son continuas y \( f_n \rightarrow  f \) entonces
\( \lim_{n \to \infty} \int _{\gamma} f_n = \int _\gamma f dz \). 
#+BEGIN_EXPORT latex
\dem{ Si \( |dz| \) es la longitud de la curva, \( L \), entonces 
\( \left|\int_{\gamma} f d z-\int_{\gamma} f_{n} d z\right| \leq \int_{\gamma}\left|f-f_{n}\right||d z|<\epsilon L \) }.
#+END_EXPORT

También, si \( \sum f_n \) converge uniformemente a \( F \), entonces \( \sum
_{n=1}^{\infty} \int _\gamma f_n \; \text{d}z  = \int _\gamma F \; \text{d}z
\). 
#+BEGIN_EXPORT latex
\dem{ \(
\int_{\gamma}\left(\sum_{n=1}^{\infty} f_{n}\right) d z =\int_{\gamma}\left(\lim _{n \rightarrow \infty} F_{n}\right) d z=\lim _{n \rightarrow \infty} \int_{\gamma} F_{n} d z 
=\lim _{n \rightarrow \infty} \int_{\gamma}\left(\sum_{k=1}^{n} f_{k}\right) d z=\lim _{n \rightarrow \infty} \sum_{k=1}^{n} \int_{\gamma} f_{k} d z=\sum_{n=1}^{\infty} \int_{\gamma} f_{n} d z
 \)  }
#+END_EXPORT


\propo{4.3.1} Sean \( f, \gamma \), \( \gamma: [a,b] \rightarrow  \mathbb{C} \) de clase \( \mathbb{C}^1 \). Si
\( F \) es una primitiva de \( F \), se tiene que \( \int _\gamma f \; \text{d}
z   \) = F(\gamma(a)) - F(\gamma(b)).
#+BEGIN_EXPORT latex
\dem{ Si \( \int _\gamma f \; \text{d}z = \int_ { a }^{ b } f(\gamma(t))\gamma'(t) \; \text{d}t   \), como la derivada de 
\( F(\gamma(t)) = F'(\gamma(t)) \) es \(F'(\gamma(t))\gamma'(t) = f(\gamma(t))\gamma'(t) \); por el Teorema Fundamental del Cálculo se cumple 
que \(\int_{\gamma} f d z =\int_{a}^{b}[F(\gamma(t))]^{\prime} d t=F(\gamma(b))-F(\gamma(a)) \)}
#+END_EXPORT

\propo{4.3.2} Sea \( f \) y \( \gamma_1, \gamma_2 \) tales que \( \gamma_1(a) =
\gamma_2(a) \) y \( \gamma_1(b) = \gamma_2(b) \). Entonces \( \int _{\gamma_1}f
\; \text{d}z  = \int _{\gamma_2}f \; \text{d}z  \).


\tma{4.4.1 (Preliminar del T de Cauchy)} Sea \( f \) analítica y \( \gamma
\subset A \) es una curva cerrada y su interior. Entonces \( \int _\gamma f \;
\text{d}z  = 0 \).
#+BEGIN_EXPORT latex
\dem{ La fórmula de Green indica que \( \int_{\gamma} P(x, y) d x+Q(x, y) d y=\iint_{A}\left[\frac{\partial Q}{\partial x}(x, y)-\frac{\partial P}{\partial y}(x, y)\right] d x d y \)
Con \( A \) el interior de \( \gamma \). Si describimos \( f = u(x,y) + iv(x,y) \) operando
tenemos que 
\(\int_{\gamma} f d z =\int_{\gamma}(u+i v)(d x+i d y) 
=\int_{\gamma}(u d x-v d y)+i \int_{\gamma}(u d y+v d x)\). Aplicando el teorema de Green 
tenemos que \( \int_{\gamma} f d z=\iint_{A}\left[-\frac{\partial v}{\partial x}-\frac{\partial u}{\partial y}\right] d x d y+\iint_{A}\left[\frac{\partial u}{\partial x}-\frac{\partial v}{\partial y}\right] d x d y \)
y, por las ecs. de Cauchy-Riemman, \( - \frac{\partial v}{\partial x} - \frac{\partial u}{\partial y} = 
\frac{\partial u}{\partial y} - \frac{\partial u}{\partial y} = 0\). Ídem para la segunda integral.  }
#+END_EXPORT
 
\tma{4.4.2 (T de Cauchy-Goursat para el triángulo)} Sea \( f: A \rightarrow
\mathbb{C} \), \( A \subset \mathbb{C} \) abierto, y \( f \) analítica en \(  A\
\{ p \}\). Si \( T \) es el triángulo cerrado contenido en \( A \), se tiene \(
\int _{\partial T} f \; \text{d} z = 0   \).

\tma{4.4.3 (T de Cauchy para un conjunto convexo)}. Sea \( f \) analítica en \(
A\{p\} \) con \( p \in A \) y continua en \( A \). Entonces   \(
\int _{\partial T} f \; \text{d} z = 0   \) para todo camino cerrado y
rectificable en \( A \).

#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT

* Consecuencias del Teorema de Cauchy
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT


\defi{5.0} Llamamos *índice* de \( \gamma \) respecto de \( \alpha \),
representado por \( Ind_{\gamma}(\alpha) \) a la integral 
\[ Ind_{\gamma}(\alpha) = \frac{1}{2\pi i}\int _\gamma \frac{\text{d}
z}{z-\alpha}   \]
Intuitivamente \( Ind_\gamma(\alpha) \) representa el número de vueltas de \(
\gamma \) respecto de \( \alpha \).
#+BEGIN_EXPORT latex
\dem{ La función \( \frac{1}{z-\alpha} \) admite la primitiva \( \log{(z - \alpha)} \) en todo entorno excepto 
para \( \alpha \). Subdividimos \( \gamma \) en subarcos suficientemente pequeños \( \gamma_1, \gamma_2, \cdots, \gamma_n \), tal que
\( \gamma_i = z_iz_{i+1}; z_i,z_{i+1} \in \gamma \). Así, la integral se puede calcular como 
\( \frac{1}{2\pi i} \int _\gamma  \frac{\text{d} z}{z - \alpha} =
 \sum _{j=1}^{n-1} \frac{1}{2\pi i} \int _{\gamma_j}  \frac{\text{d} z}{z - \alpha} 
= \sum_{j=1}^{n-1} \frac{1}{2 \pi i}[\ln (z_{j+1}-\alpha)-\ln (z_{j}-\alpha)] = 
 \sum_{j=1}^{n-1} \frac{1}{2 \pi i}[\ln |(z_{j+1}-\alpha)|-\ln |(z_{j}-\alpha)|]+\sum_{j=1}^{n-1} 
\frac{1}{2 \pi}[\operatorname{Arg}(z_{j+1}-\alpha)-\operatorname{Arg}(z_{j}-\alpha)]
 \). La primera suma es 0 por ser teléscopica y \( z_1 = z_n \), luego 
\( \frac{1}{2\pi i} \int _\gamma  \frac{\text{d} z}{z - \alpha} = \sum_{j=1}^{n-1} 
\frac{1}{2 \pi}[\operatorname{Arg}(z_{j+1}-\alpha)-\operatorname{Arg}(z_{j}-\alpha)] \). Cada elemento de la suma
es una variación de la circunferencia, y en conjunto representa el número de vueltas
recorrido.}
#+END_EXPORT

\tma{5.1.1} Si \( \gamma \) es diferenciable cerrado, \( \gamma^* \) su
interior, entonces \( Ind_\gamma(\alpha) \) es
entero si \( \alpha \in \gamma^* \), o es cero si \( \alpha \in
\mathbb{C}/\gamma^* \). 

\tma{5.2.1 (Fórmula integral de Cauchy)} Sea \( f: A \rightarrow  \mathbb{C} \),
y sea \( \gamma \) un camino cerrado en \( A \). Entonces para todo \( z \in A
\) tal que \( z \not \in \gamma^* \)
 se tiene \[ f(z) Ind_\gamma(z) = \frac{1}{2\pi i}\int _\gamma
\frac{f(\zeta)}{\zeta - z} \text{d}\zeta   \]
#+BEGIN_EXPORT latex
\dem{  Definimos $g: A \rightarrow \mathbb{C}$ mediante:
$$
g(\zeta)=\left\{\begin{array}{cccc}
\frac{f(\zeta)-f(z)}{\zeta-z} & \text { para } & \zeta \in A, & \zeta \neq z \\
f^{\prime}(z) & \text { para } & \zeta=z
\end{array}\right.
$$
donde $z \in A \backslash \gamma^{*}$ es un punto fijo. La función $g$ es analítica para $\zeta \neq z$ y
$
g^{\prime}(\zeta)=\frac{(\zeta-z) f^{\prime}(\zeta)-f(\zeta)+f(z)}{(\zeta-z)^{2}}
$
y es continua para $\zeta=z$ pues
$
\lim _{\zeta \rightarrow z} g(\zeta)=f^{\prime}(z)
$.
Por tanto podemos aplicar el Teorema de Cauchy-Goursat y 
$
\frac{1}{2 \pi i} \int_{\gamma} g(\zeta) d \zeta=0
$ y como $z \notin \gamma^{*},$ se puede escribir
$
0 =\frac{1}{2 \pi i} \int_{\gamma} \frac{f(\zeta)-f(z)}{\zeta-z} d \zeta=\frac{1}{2 \pi i} \int \frac{f(\zeta)}{\zeta-z} d \zeta 
-\frac{f(z)}{2 \pi i} \int_{\gamma} \frac{d \zeta}{\zeta-z} \iff \frac{f(z)}{2 \pi i} 
\int_{\gamma} \frac{d \zeta}{\zeta-z}=\frac{1}{2 \pi i} \int_{\gamma} \frac{f(\zeta)}{\zeta-z} d \zeta
$
es decir
$f(z) \operatorname{Ind}_{\gamma}(z)=\frac{1}{2 \pi i} \int_{\gamma} \frac{f(\zeta)}{\zeta-z} d \zeta$ }
#+END_EXPORT

\tma{5.3.1 (Teorema de Taylor)} 
Sea $f$ holomorfa, $A \subset \mathbb{C}$ abierto,
y $\alpha \in A$. Sea $d>0$ la distancia de $\alpha$ a la frontera de $A$; 
entonces para todo $z \in B(\alpha, d)$
$$
f(z)=\sum_{n=0}^{\infty} \frac{f^{(n)}(\alpha)}{n !}(z-\alpha)^{n}
$$
El radio de convergencia es mayor o igual que
$d$, y en $B(\alpha, d)$ su suma es $f(z)$. 
Además las derivadas sucesivas $f^{(n)}$ $(\alpha)$ de $f$ en $\alpha$ vienen dadas por
$$
f^{(n)}(\alpha)=\frac{n !}{2 \pi i} \int_{\gamma} \frac{f(\zeta)}{(\zeta-\alpha)^{n+1}} d \zeta
$$
donde $\gamma$ es una circunferencia de centro $\alpha$ y radio $r$, con
$0<r<d$.

\tma{5.4.1 (Desigualdades de Cauchy)} Si \( f \) es analítica y \( B(\alpha, d)
\subset A \) entonces 
\(|f^{(n)}(\alpha)| \le \frac{n!M(r)}{r^n} \), con \( M(r) =
\max_{|z|=r<d}|f(z)| \)

\tma{5.4.2 (Teorema de Liouville)} Si \( f \) es entera (analítica en todo \(
\mathbb{C} \)) y acotada, entonces es constante.
#+BEGIN_EXPORT latex
\dem{  Por ser $f$ analítica existe un desarrollo
$
f(z)=\sum_{n=0}^{\infty} a_{n} z^{n}
$
con radio de convergencia infinito. Sea $K$ una cota de $f$, es decir
$
|f(z)|<K, \text { para todo } z \in \mathbb{C}
$
entonces de las desigualdades de Cauchy se obtiene
$
\left|a_n|<\frac{K}{r^n}, n=1, 2, \cdots
$
. Como \( r \rightarrow \infty \), \( a_n \rightarrow 0 \) y \( f(z) = a_0 \). }
#+END_EXPORT

\tma{5.5.1} Sea \( \{ f_n \}_{n \in \mathbb{N}} \) una sucesión de funciones 
analíticas en \( A \) que converge uniformemente en todo compacto de \( A \).
Entonces la sucesión \(  \{ f'_n \} \) converge uniformemente en todo compacto
de \( A \). Además, si \(  \lim_{n \to \infty} f_n(z) = f(z) \) entonces \(
\lim_{n \to \infty} f'_n(z) = f'(z) \) para todo \( z \in A \).

#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=7cm]{imagenes/T-5_5_1.png}
\end{figure}
#+END_EXPORT

#+BEGIN_EXPORT latex
\dem{   Bastará demostrar la convergencia uniforme de la sucesión
$\left\{f_{n}^{\prime}\right\}$ a $f^{\prime}$ en todo círculo $B \subset A,$ pues todo compacto
 $K \subset A$ puede ser recubierto por una cantidad finita de círculos.
Sea $\gamma^{*} \subset A$ una circunferencia concéntrica con $B$ con $r = r_\gamma - r_B$.
 Sea $z \in B$ y $\gamma_{z}$ la circunferencia de centro $z$ y 
radio $r$. Entonces
$
f^{\prime}(z)=\frac{1}{2 \pi i} \int_{\gamma_{z}} \frac{f(\zeta)}{(\zeta-z)^{2}} d \zeta, \quad f_{n}^{\prime}(z)
=\frac{1}{2 \pi i} \int_{\gamma_{z}} \frac{f_{n}(\zeta)}{(\zeta-z)^{2}} d \zeta
$
de donde
$
|f^{\prime}(z)-f_{n}^{\prime}(z)|  \leq \frac{1}{2 \pi} \int_{\gamma_{z}} 
\frac{\left|f(\zeta)-f_{n}(\zeta)|}{|\zeta-z|^{2}}|d \zeta|
 \leq \frac{1}{2 \pi} \frac{M_{n}}{r^{2}} 2 \pi r=\frac{M_{n}}{r}
$
donde $M_{n}$ es $\max(\left|f(\zeta)-f_{n}(\zeta)\right|)$
en $\gamma_z$.
Puesto que $\left\{f_{n}\right\}$ converge uniformemente sobre todo círculo 
cerrado, se tiene que
$
\lim _{n \rightarrow \infty} M_{n}=0
$ de tal manera que $\frac{M_{n}}{r}<\epsilon$
para $n \geq n_{0}$, y $z \in B$ .
}
#+END_EXPORT

\defi{5.6} \( f \) en \( A \subset \mathbb{C} \) tiene la *propiedad de la media*
si para todo cerrado \( \overline{D}(\alpha, r) = \{ z \;|\; |z - \alpha| \le r
\} \subset A \), el valor \( f(\alpha) \) en el centro es la media de f en la
circunferencia:
\[ f(\alpha) = \frac{1}{2 \pi} \int_{0}^{2 \pi} f\left(\alpha+r e^{i t}\right) d t \]

\propo{5.6.1} Toda función analítica \( f \) en \(  A \) tiene la propiedad de
la media.

\tma{5.6.1 (Principio del módulo máximo)}
Sea \( f \) analítica en \( A \), abierto conexo. Entonces para todo \( \alpha
\in A \) en cualquier entorno de \( \alpha \) existe \(  \beta \in A \) para el
cual \( |f(\alpha)| < |f(\beta)| \).

\lema{5.7.1 (Lema de Schwarz)}
Sea \( f: B(0,1) \rightarrow  B(0,1) \) analítica. \( |f(z)| < 1 \) para todo \( z
\in B(0,1) \) y \( f(0) = 0 \). Entonces se tiene $|f(z)| \leq|z|$ para todo
 $z \in B(0,1)$ y $\left|f^{\prime}(0)\right| \leq 1$. 
Además, si para un $z_{0} \in B(0,1), z_{0} \neq 0$, se tiene 
$\left|f\left(z_{0}\right)\right|=\left|z_{0}\right|$, o si se verifica 
$f^{\prime}(0)=1$, entonces $f(z)$ es de la forma $f(z)=c z$, con $|c|=1$

#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT

 

* Teorema general de Cauchy
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT

\defi{6.1.1} Dos caminos \( \gamma_0, \gamma_1 \) con \( \gamma_0^*, \gamma_1^*
\subset A \) son \(  A \)-homótopos si existe una aplicación \( h \):
\[ \begin{aligned}
h: &\; I \times  I  \longrightarrow A \\
&\; (s,t) \longmapsto h((s,t)) = \gamma_s(t)
\end{aligned} \]

Si \( \gamma_0, \gamma_1 \) tienen los mismos extremos, se exige que \( h(s,0) =
\gamma_0(0) = \gamma_1(0) \) y  \( h(s,1) =
\gamma_0(1) = \gamma_1(1) \). Finalmente, si los caminos son cerrados, \( h(s,0)
= h(s,1)\).

\( \gamma_0, \gamma_1 \) son *\( A \)-homotópos* cuando \( \gamma_0 \) se puede
deformar a \( \gamma_1 \) continuamente a través de una familia de caminos \(
\gamma_s \). Un camino \( \gamma \) es homotópico a \( z_0 \in A \) cuando \(
\gamma \) es homotópico al camino constante \( \gamma_{z_0} \).

\tma{6.1.1 (Teorema de Cauchy, versión homotópica)} 
Sea $f: A \rightarrow \mathbb{C}, A$ abierto una función analitica y sean
 $\gamma_{0}, \gamma_{1}$ dos caminos tales que
 $\gamma_{0}(0)=\gamma_{1}(0), \gamma_{0}(1)=\gamma_{1}(1)$, entonces
$$
\int_{\gamma_{0}} f d z=\int_{\gamma_{1}} f d z
$$
También si $\gamma_{0}, \gamma_{1}$ son cerrados y homotópicos obtenemos
 la misma conclusión.

\defi{6.2.1} Dos caminos cerrados $\gamma_{0}, \gamma_{1}$ contenidos en
 el mismo abierto $A$ son *\(A\)-homólogos* cuando
$$
\operatorname{Ind}_{\gamma_{0}}(\alpha)=\operatorname{Ind}_{\gamma_{1}}(\alpha)
$$
para todo $\alpha \notin A$

\tma{6.2.1} Si \( \gamma_0, \gamma_1 \) son cerrados en \( A \), y \( \gamma_0,
\gamma_1 \) son \( A \)-homótopos, son también \( A \)-homólogos. Si \( \gamma_0
\) es homótopo a un punto en \( A \), entonces es \( A \)-homólogo a cero.

\tma{6.2.2 (Teorema de Cauchy, versión homológica)} 
Sea $f: A \rightarrow \mathbb{C}, A$ abierto una función analitica y sean $\gamma_{0}, \gamma_{1}$ dos ciclos $A$ homológos, entonces
$$
\int_{\gamma_{0}} f d z=\int_{\gamma_{1}} f d z
$$

\defi{6.3.1}/\tma{6.3.1} Un abierto conexo no vacío \( A \subset \mathbb{C} \) es
simplemente conexo si todo cerrado \( \gamma \subset A \) es \( A \)-homótopo a
cero.
Si \( f \) es analítica en \( A \), simplemente conexo, entonces \( \int _\gamma
f \; \text{d} z = 0   \) para todo camino cerrado y rectificable en \( A \).

\tma{6.3.2} Sea \( A \in \mathbb{C} \) un dominio, entonces las siguientes
afirmaciones son equivalentes:
\vspace{-1em}
- \( A  \) es simplemente conexo
- Todo ciclo \( \gamma \) contenido en \( A \) es homólogo a 0.
- \( \hat{\mathbb{C}} \backslash A \) es conexo

\vspace{-1em}
** Desarrollo en serie de Laurent
\vspace{-1em}
\tma{6.4.1 (Series de Laurent)} Sea \( f(z) \) analítica en la corona circular
\( A = \{ z \;|\; r < |z-\alpha| < R \} \), donde $r$ puede ser 0 y $R$
infinito. 
Entonces existen dos desarrollos en serie
según las potencias de $z-\alpha$ y de $(z-\alpha)^{-1}$
\(\sum_{n=0}^{\infty} a_{n}(z-\alpha)^{n}, \sum_{n=1}^{\infty} \frac{b_{n}}{(z-\alpha)^{n}}\)
convergentes en $A$ y tales que
$$
f(z)=\sum_{n=0}^{\infty} a_{n}(z-\alpha)^{n}+\sum_{n=1}^{\infty} \frac{b_{n}}{(z-\alpha)^{n}}
$$
para $z \in A$. Además estas series convergen uniformemente en toda corona
cerrada $A^{\prime} \subset A$ de la forma \(
A^{\prime}=\left\{z\left|r<r^{\prime} \leq\right| z-\alpha | \leq
R^{\prime}<R\right\} \)
$y$ los coeficientes $a_{n}, b_{n}$ vienen dados por
\[\begin{aligned}
a_{n} &=\frac{1}{2 \pi i} \int_{\gamma} \frac{f(\zeta)}{(\zeta-\alpha)^{n+1}} d \zeta \\
b_{n} &=\frac{1}{2 \pi i} \int_{\gamma} f(\zeta)(\zeta-\alpha)^{n-1} d \zeta
\end{aligned}\]
donde $\gamma$ es una circunferencia dada por \(
\gamma(t)=\alpha+\rho e^{i t}, t \in[0,2 \pi] \)
siendo $\rho$ un radio cualquiera entre $r$ y $R$.
#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=3cm]{imagenes/laurent.png}
\end{figure}
#+END_EXPORT
#+BEGIN_EXPORT latex
\dem{Sean $r_{1}, r_{2}$ dos radios tales que $r<r_{1}<r_{2}<R,$ y sean $\gamma_{1}, \gamma_{2}$ las circunferencias
$
\gamma_{1}(t)=\alpha+r_{1} e^{i t}, \gamma_{2}(t)=\alpha+r_{2} e^{i t}, t \in[0,2 \pi]
$
tal que si $z$ está entre ambas se tiene
 $\operatorname{Ind}_{\gamma_{2}}(z)=1, \operatorname{Ind}_{\gamma_{1}}(z)=0$.
Sea $r_{1}<|z-\alpha|<r_{2},$ y supongamos que $z$ no pertenece al segmento $\gamma_{3}$ (si no movemos $\gamma_3$).
Sea $\Gamma=\gamma_{2}-\gamma_{3}-\gamma_{1}+\gamma_{3}$; entonces $z$ está en el recinto simplemente
 conexo encerrado por $\Gamma$ y de la
Fórmula integral de Cauchy obtenemos
$$
f(z) =\frac{1}{2 \pi i} \int_{\Gamma} \frac{f(\zeta)}{\zeta-z} d \zeta 
=\frac{1}{2 \pi i} \left( \int_{\gamma_{2}} \frac{f(\zeta)}{\zeta-z} d \zeta- \int_{\gamma_{1}} \frac{f(\zeta)}{\zeta-z} d \zeta \right)
$$
Utilizaremos ahora desarrollos en serie similares a los de Taylor. 
Para $\zeta \in \gamma_{2}$ y $z$ en el interior de $\gamma_{2}$ tendremos
$$
\frac{1}{\zeta-z}=\frac{1}{\zeta-\alpha} \cdot \frac{1}{1-\frac{z-\alpha}{\zeta-\alpha}}=\sum_{n=0}^{\infty} \frac{(z-\alpha)^{n}}{(\zeta-\alpha)^{n+1}}
$$
y para $\zeta \in \gamma_{1}$ y $z$ exterior a $\gamma_{1}$ tendremos
$$
-\frac{1}{\zeta-z}=\frac{1}{z-\alpha} \frac{1}{1-\frac{\zeta-\alpha}{z-\alpha}}=\sum_{n=1}^{\infty} \frac{(\zeta-\alpha)^{n-1}}{(z-\alpha)^{n}}
$$
siendo convergentes las series geométricas y 
uniformemente convergentes en $\zeta \in \gamma_{2}$ y $\zeta \in \gamma_{1}$ respectivamente.
Integrando término a término ambos desarrollos se tiene
$$
\begin{array}{c}
\frac{1}{2 \pi i} \int_{\gamma_{2}} \frac{f(\zeta)}{\zeta-z} d \zeta=\sum_{n=0}^{\infty} \frac{1}{2 \pi i}\left(\int_{\gamma_{2}} 
\frac{f(\zeta)}{(\zeta-\alpha)^{n+1}} d \zeta\right)(z-\alpha)^{n} \\
-\frac{1}{2 \pi i} \int_{\gamma_{1}} \frac{f(\zeta)}{\zeta-z} d \zeta=\sum_{n=1}^{\infty} \frac{1}{2 \pi i}\left(\int_{\gamma_{1}}
 f(\zeta)(\zeta-\alpha)^{n-1} d \zeta\right) \frac{1}{(z-\alpha)^{n}}
\end{array}
$$
Puesto que los caminos $\gamma_{1}, \gamma_{2}, \gamma$ son A-homótopos y las funciones
$\frac{f(\zeta)}{(\zeta-\alpha)^{n+1}}, f(\zeta)(\zeta-\alpha)^{n-1}$
son analíticas en $A$, se tiene
$$
\begin{array}{c}
\frac{1}{2 \pi i} \int_{\gamma_{2}} \frac{f(\zeta)}{(\zeta-\alpha)^{n+1}} d \zeta=\frac{1}{2 \pi i} \int_{\gamma} \frac{f(\zeta)}{(\zeta-\alpha)^{n+1}} d \zeta=a_{n} \\
\frac{1}{2 \pi i} \int_{\gamma_{1}} f(\zeta)(\zeta-\alpha)^{n-1}=\frac{1}{2 \pi i} \int_{\gamma} f(\zeta)(\zeta-\alpha)^{n-1}=b_{n}
\end{array}
$$
Por tanto concluimos
$$
f(z)=\sum_{n=0}^{\infty} a_{n}(z-\alpha)^{n}+\sum_{n=1}^{\infty} b_{n} \frac{1}{(z-\alpha)^{n}}, z \in A
$$
Queda por probar la convergencia uniforme en una corona cerrada contenida en $A$.
Sean $z_{1}, z_{2}$ puntos de $A$ tales que
$r<\left|z_{1}-\alpha\right|<r^{\prime}<R^{\prime}<\left|z_{2}-\alpha\right|<R$.
Como $z_{2} \in A,$ la serie de potencias
$\sum_{n=0}^{\infty} a_{n}(z-\alpha)^{n}$
converge uniformemente en el círculo cerrado de centro $\alpha$ 
y radio $R^{\prime}<\left|z_{2}\right|$. Análogamente, puesto que $z_{1} \in A$, la serie
$\sum_{n=1}^{\infty} b_{n}\left(\frac{1}{z_{1}-\alpha}\right)^{n}$
converge y la serie
$\sum_{n=1}^{\infty} b_{n}\left(\frac{1}{z-\alpha}\right)^{n}$
convergerá uniformemente para $|z-\alpha| \geq r^{\prime}$ con $r^{\prime}>\left|z_{1}-\alpha\right|$, pues en estas
condiciones
$\left|\frac{1}{z-\alpha}\right| \leq \frac{1}{r^{\prime}}<\left|\frac{1}{z_{1}-\alpha}\right|$. 
Análogamente se comprueba la convergencia uniforme en \( |z-\alpha| < R' \) de 
la serie \( \sum _{n=0}^{\infty}a_n(z-\alpha)^n \).}
#+END_EXPORT
#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT


\vspace{-1.5em}
* Ceros de las \begin{aligned}
  f: &\; X \longrightarrow Y \\
  &\; x \longmapsto f(x) = 
  \end{aligned}iones analíticas. Singularidades aisladas.
\vspace{-1.5em}
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT
\tma{7.1.1} Sea \( f: A \rightarrow  \mathbb{C} \), con \(  A  \) un dominio. 
El conjunto \( \mathbb{Z}(f) \), los ceros de \( f \), o coincide con \( A \) (\(f
= 0\)) o no tiene puntos de acumulación en \( A \). En este último caso, para cada
\( \alpha \in A  \) existe un \( m \in \mathbb{N} \) tal que \( f(z) = (z -
\alpha)^m g(z) \), con \( g(\alpha) \neq 0 \).

\tma{7.1.2 (Ppo de Identidad)} Si \( f_1, f_2 \) son funciones analíticas en \(
A \) tal que \( f_1(z) = f_2(z), z \in B \subset A \); si \( B \) tiene punto de
acumulación en \( A \) entonces \( f_1 = f_2 \) en \( A \).

\defi{7.2.0} \( f \) tiene una *singularidad aislada* en \( \alpha \in A  \)
si \( f \) es analítica en \( A/ \{ \alpha \} \) pero desconocemos el
comportamiento en \( \alpha \).

\defi{7.2.1} \( f \) tiene una *singularidad evitable* en \( \alpha \) si tiene
una singularidad aislada pero se puede encontrar un valor \( b \in \mathbb{C} \)
tal que poniendo \( f(\alpha) = b \), \( f \) es analítica en \( A \).

\tma{7.2.1} Sea \( \alpha \) aislada para \( f \) en \( A \), y supongamos \( f
\) *acotada* en un círculo perforado \( B^*(\alpha, r) \) contenido en \( A / \{
\alpha \} \). Entonces la singularidad es evitable.
#+BEGIN_EXPORT latex
\dem{ Definamos la función $h: A \rightarrow \mathbb{C}$ mediante
$$
h(z)=\left\{\begin{array}{ccc}
(z-\alpha)^{2} f(z) & \text { para } & z \in A \backslash\{\alpha\} \\
0 & \text { para } & z=\alpha
\end{array}\right.
$$
Por la hipótesis de acotación (pues \( f \) es acotada) 
 existe $h^{\prime}(\alpha)$ y
$h^{\prime}(\alpha)=0$. Luego $h$ es analítica en $A$ y existe un desarrollo 
en serie de potencias en un \( B(\alpha, r'), r' \ge r \), donde tendremos que
$h(z)=\sum_{n=0}^{\infty} a_{n}(z-\alpha)^{n}$
para todo $z$ en dicho círculo y, por tanto, también en $B(\alpha, r)$. 
Se tiene que  $a_{0}=h(\alpha)=0, a_{1}=h^{\prime}(\alpha)=0$ y, considerando entonces la función 
analítica en $B(\alpha, r)$ definida por
$
\sum_{n=0}^{\infty} a_{n+2}(z-\alpha)^{n}
$, vale $a_{2}$ en $z=\alpha$ y coincide con $f$ en $B^{*}(\alpha, r),$ luego
 concluimos que $\alpha$ es una singularidad evitable para $f$.}
#+END_EXPORT

\tma{7.2.2 (Weierstrass)} Sea \( \alpha \in A \) una singularidad aislada para
\( f \) en \( A / \{ \alpha \} \). Entonces (1) \( f \) tiene una singularidad
evitable en \( \alpha \), (2) existen complejos \( c_1, \cdots, c_m \neq 0 \) 
y la función \( f(z) - \sum _{k=1}^{m} \frac{c_k}{(z-\alpha)^k} \) tiene una
singularidad evitable en \( \alpha \), o (3) para todo \( B(\alpha, r) \subset A, r > 0 \)
la imagen de \( f \) en \( B^*(\alpha, r) \) es densa en \( \mathbb{C} \).

\defi{7.2.2} Sea \( A \subset \overline{\mathbb{C}} \) abierto y \( f \)
analítica en \( A \backslash \{ \infty \} \). Se dice que \( f \) tiene una
singularidad evitable en \( \infty \), un polo de orden \( m \) o una
singularidad esencial, si la función \( \phi: B \rightarrow  \mathbb{C} \), \(
\phi(z) = f(\frac{1}{z}) \), con \( B = \{ z \;|\; \frac{1}{z} \in A \} \) tiene
una singularidad de tal tipo en \( z = 0 \).

\tma{7.2.3} Si existe una singularidad aislada en \( \infty  \) entonces (1) \(
f \) tiene una singularidad evitable sii existe un entorno perforado de \(
\infty \); (2) \( f \) tiene un polo de orden \( m \) si existe un polinomio \(
h(z) = a_1z + \cdots + a_mz^m \neq 0 \) tal que \( f(z) - h(z) \) está acotada
en \( \{ z \;|\; |z| > r \} \); (3) para todo \( r \) la imagen de \( \{ z
\;|\; |z| > r \}\) es densa en \(\mathbb{C} \).


\defi{7.3.1} Diremos que \( f_ A \rightarrow  \mathbb{C} \), \( A \subset
\mathbb{C} \) abierto es meromorfa si existe un conjunto \( P \subset A \), sin
puntos de acumulación en \( A \), tal que \( f \) es analítica en \( A
\backslash P \) y \( f \) presenta en cada \( p \in P \) una singularidad
aislada, que es un polo.

\tma{7.3.1} \( f(z) \) tiene un *polo* de orden \( m \) en \( \alpha \in \mathbb{C} \) sii existe
un entero \( m > 0 \) y un entorno \( U_\alpha 
\subset A \) de definición de \( f \) tal que la función \( g(z) = f(z)(z -
\alpha)^m \) es analítica en \( U_\alpha \) y \( g(\alpha) \neq 0 \). 
#+BEGIN_EXPORT latex
\dem{ Sea
$$
p(z)=\sum_{n=1}^{m} \frac{c_{n}}{(z-\alpha)^{n}}
$$
la parte principal del polo, de tal forma que $h=f-p$
es analítica en un entorno $U(\alpha)$ de $\alpha$ y por tanto también lo será la función
$h(z)(z-\alpha)^{m}$. \\Como
$p(z)(z-\alpha)^{m}=c_{m}+c_{m-1}(z-\alpha)+\ldots+c_{1}(z-\alpha)^{m-1}$
es también analítica, también lo será la función
$f(z)(z-\alpha)^{m}=h(z)(z-\alpha)^{m}+p(z)(z-\alpha)^{m}$.
Llamando $g(z)$ a esta función, obtenemos
$g(\alpha)=c_{m} \neq 0$.\\
Inversamente, si para un entero $m>0$ se tiene que $g(z)=f(z)(z-\alpha)^{m}$ 
es analítica y $g(\alpha) \neq 0$ en un entorno $U(\alpha)$ de $\alpha$ entonces admitirá 
un desarrollo en serie de potencias de $z-\alpha$;
$f(z)(z-\alpha)^{m}=\sum_{n=0}^{\infty} b_{n}(z-\alpha)^{n}, \text { con } b_{0} \neq 0$.
De esta igualdad resulta si $z \neq \alpha$
$$
f(z) =\frac{1}{(z-\alpha)^{m}} \sum_{n=0}^{\infty} b_{n}(z-\alpha)^{n}
=p(z)+\sum_{n=m}^{\infty} b_{n}(z-\alpha)^{n-m}
$$
donde
$$
p(z)=\sum_{n=1}^{m} \frac{b_{m-n}}{(z-\alpha)^{n}}, \text { con } b_{0} \neq 0
$$
De aquí se deduce que $\alpha$ es un polo de orden $m$ y su parte principal es $p$.}
#+END_EXPORT

\tma{7.3.2} Si \( f(z) \) es analítica en el abierto \( A \) y si \( f(z) \)
tiene un cero de orden \( m \) en \( \alpha \in A \), entonces la función \(
g(z) = \frac{1}{f(z)} \) tiene un polo de orden \( m \) en \( \alpha \).
Repíprocamente, si \( f(z) \) tiene un polo de orden \( m \) en \( \alpha \),
entonces \( g(z) = \frac{1}{f(z)} \) es analíotica en un entorno de \( \alpha \)
y tiene un cero de orden \( m \) en \( \alpha \).

\defi{7.3.2} Si \( f(z) \) es una función con un polo de orden \( m \) en \(
\alpha \) y su parte principal es \( p(z) = \sum _{n=1}^{m}
\frac{c_m}{(z-\alpha)^n} \), llamaremos *residuo* de \( f \) en \( \alpha \) al
coeficiente \( c_1 \) del término \( \frac{1}{z - \alpha}\), y se designa por \(
Res(f, \alpha) \).

\tma{7.3.3 (Residuos para funciones meromorfas)}
 Sea $A \subset \mathbb{C}$ un abierto simplemente conexo y $f(z)$ una función
 meromorfa con polos $\alpha_{1}, \alpha_{2}, \ldots, \alpha_{r}$. 
Sea $\gamma$ un camino cerrado contenido en $A$ que no pasa por ninguno de 
los polos. Entonces se tiene
$$
\int_{\gamma} f(z) d z=2 \pi i \sum_{i=1}^{r} \operatorname{Ind}_{\gamma}\left(\alpha_{i}\right) \operatorname{Res}\left(f, \alpha_{i}\right)
$$
#+BEGIN_EXPORT latex
\dem{Sean los polos $\alpha_{1}, \ldots, \alpha_{r}$ de multiplicidades
 $m_{1}, \ldots, m_{r}$ y sean
$p_{i}(z), i=1, \ldots, r$ sus partes principales con
$$
p_{i}(z)=\sum_{n=1}^{m_{i}} \frac{c_{i, n}}{\left(z-\alpha_{i}\right)^{n}}, i=1, \ldots, r
$$.
Entonces la función $f-\sum_{i=1}^{r} p_{i}$ es analitica en $A$ pues ambas
 funciones $f$ y $\sum_{i=1}^{r} p_{i}$ son meromorfas en $A$, con los mismos polos, 
cuyas partes principales se cancelan en cada polo.
Así pues podemos aplicar el Teorema de Cauchy para
dominios simplemente conexos (\tma{7.4.1}) y obtenemos 
$$
\int_{\gamma} f-\left(p_{1}+p_{2}+\ldots+p_{r}\right) d z=0 \rightarrow 
\int_{\gamma} f d z=\sum_{i=1}^{r} \int_{\gamma} p_{i} d z
$$
Por otra parte
$$
\begin{aligned}
\int_{\gamma} p_{i}(z) &=\int_{\gamma} \frac{c_{i, 1}}{z-\alpha_{i}} d z+\ldots+\int_{\gamma} \frac{c_{i, m_{i}}}{\left(z-\alpha_{i}\right)^{m_{i}}} d z \\
&=2 \pi i c_{i, 1} \operatorname{Ind}_{\gamma}\left(\alpha_{i}\right)
\end{aligned}
$$
las últimas $m_{i}-1$ integrales son nulas pues las funciones integrando tienen
 primitiva. De ambas igualdades se concluye el enunciado del teorema.}
#+END_EXPORT


\obs{7.3.3} Si \( f \) es meromorfa con polo en \( \infty \); para el desarrollo
en serie \( f(z) = \sum _{n=0}^{m}a_nz^n + \sum _{n=1}^{\infty}b_n \frac{1}{z_n}
\), \( Res(f, \infty) = -b_1 \).
#+BEGIN_EXPORT latex
\dem{ Los residuos pertenecen a los \textbf{diferenciales} de las funciones, no a las funciones en sí.
Por tanto, dado el diferencial \( f(z) dz \) con el cambio de variable 
\( z = 1/w \) tenemos que \( f(z)dz = f(1/w)(1/w)'dw = f(1/w)(-1/w^2)dw \).
Entonces, \( Res(f, \infty) = Res(- \frac{f(1/z)}{z^2}, 0) \). 
Con este cambio, 
la representación por series \( f(z) =  \sum _{n=0}^{m}a_nz^n + 
\sum _{n=1}^{\infty}b_n \frac{1}{z^n}  \) con \( z \rightarrow \infty \) pasa a ser 
\( -\frac{1}{z^2}f(\frac{1}{z}) (\sum _{n=0}^{m} a_n(\frac{1}{z})^n +
 \sum _{n=1}^{\infty}\frac{b_n}{(\frac{1}{z})^n} )\) \(  = - (\sum _{n=0}^{m} a_n(\frac{1}{z})^{n+2} +
 \sum _{n=1}^{\infty}b_nz^{n-2} \) y \( \int _\gamma - \frac{1}{z^2}f(\frac{1}{z})  \; \text{d}z  
= - \int _\gamma \frac{b_1}{z} \; \text{d}z  = -2 \pi i b_i = 2\pi i Res(f, \infty) \). 
 }
#+END_EXPORT

La opción (3) del \tma{7.2.2} se puede extender a dos teoremas extra, el segundo
más potente que el primero.

\tma{7.A (Casorati - Weierstrass)} Sea \( \alpha \) una singularidad esencial de
\( f \). Entonces para cada \( w \in \mathbb{C} \) existe una secuencia de
complejos \( \{ z_n \} \) convergente a \( \alpha \) tal que \( f(\{ z_n \})
\rightarrow w \). 

\tma{7.B (Picard)} Sea \( \alpha \) una singularidad esencial de \( f \).
Entonces, para cada \( w \in \mathbb{C} \), con una excepción a lo sumo, existe
una sucesión \( z_n \rightarrow  \alpha  \) tal que \( f(z_n) = w  \). \\ 
Por ejemplo, para \( f(z) = e^{1/z} \), que tiene una singularidad esencial en
0, queremos que \( w = 3 + i \). Entonces, la sucesión \( z_n =
\frac{1}{\log{3 + i}} = \frac{1}{\sqrt{4} + i\cdot Arg(3+i) + 2\pi n} \) cumple que
para \( n \rightarrow \infty \), \( z_n \rightarrow 0 \) y \( e^{\frac{1}{z_n}}
= e^{\sqrt{4} + i \cdot Arg(3+i) + 2\pi n} = 3+i \) para todo \( n \). La
excepción en este caso es \( w = 0 \), donde \( z_n \) no existe.

\vspace{-2em}
** Resumen de casos (según series de Laurent)
\vspace{-1.5em}
- Singularidad evitable: \( a_0 + a_1 (z - \alpha) + \cdots \)
- Polo de orden \( m \): \( \frac{a_{-m}}{(z - \alpha)^m} + \cdots +
  \frac{a_{-1}}{z-\alpha} + a_0 + a_1(z - \alpha) + \cdots \)
- Singularidad esencial: \(  \cdots +
  \frac{a_{-1}}{z-\alpha} + a_0 + a_1(z - \alpha) + \cdots \)
 
\vspace{-2em}
** Calculo de residuos para polos
\vspace{-1.5em}
- Polo simple
\vspace{-1em}
$$ f(z) = \frac{b_1}{z - \alpha} + a_0 + a_1(z -
  \alpha) + \cdots $$
$$ (z-\alpha)f(z) = b_1 + a_0(z - \alpha) + \cdots$$
$$ Res(f, \alpha) = b_1 = \lim_{z \to \alpha} (z - \alpha)f(z) $$ 

- Polo de orden m
\vspace{-1em}
$$f(z) = \frac{b_m}{(z-\alpha)^m} + \cdots + \frac{b_1}{z-\alpha} + a_0 +
a_1(z-\alpha) + \cdots$$
$$(z-\alpha)^mf(z) = b_m + \cdots + b_1(z-\alpha)^{m-1} + a_0(z-\alpha)^m +
\cdots$$
$$ Res(f, \alpha) = \frac{1}{(m-1)!} \lim_{z \to \alpha} \frac{d^{m-1}}{dz^{m-1}}((z-\alpha)^mf(z)) $$
#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT


\vspace{-1.5em}
* Aplicación del método de residuos al cálculo de integrales reales
\vspace{-1.5em}
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT

** \( \int _0^{2\pi} R(\cos \theta, \sin \theta) \; \text{d}\theta  \)
\vspace{-1.5em}
Tomamos el cambio de variable \( z = e^{i\theta} \), entonces
\[ \cos\theta = \frac{1}{2} \left(    z + \frac{1}{z} \right)  \quad
\sin\theta = \frac{1}{2i} \left(    z -
\frac{1}{z} \right) \quad  d\theta = \frac{dz}{iz}  \]

y obtenemos una integral \( \int f(z) \; \text{d}z  \) con polos dentro de \(
\gamma \),  \( \alpha_1,
\cdots, \alpha_n \), y la resolvemos como 
\[  \int _0^{2\pi} R(\cos \theta, \sin \theta) \; \text{d}\theta = \int _\gamma
f(z) \; \text{d}z  = \]\[ = 2\pi i \sum
_{i=1}^{n} \text{Res} \left( f(z), \alpha_i \right)  \]


** \( \int_{- \infty}^{+ \infty} \frac{P(x)}{Q(x)} \; \text{d} x   \)
\vspace{-1.5em}
Para resolver esta integral requerimos que *no haya polos en el eje real* y, que
\( Q(x) \neq 0 \) *en* \( \mathbb{R} \), y que
*ord(Q) \ge 2 + ord(P)*.

En estas condiciones, si \( \alpha_1, \cdots, \alpha_n \) son los polos en el
*eje imaginario POSITIVO*, entonces
\[ \int _{- \infty}^{+ \infty} \frac{P(x)}{Q(x)} \; \text{d} x  = 2\pi i \sum
_{i=1}^{n} \text{Res} \left( \frac{P(z)}{Q(z)}, \alpha_i \right)  \]

\importante Tenemos que asegurar la existencia de \( \int_{- \infty}^{+ \infty}
\frac{P(x)}{Q(x)} \; \text{d} x \), porque si no, el resultado será falso.  

** \( \int_{- \infty}^{+ \infty} \frac{P(x)}{Q(x)} e^{iax} \; \text{d} x   \)
\vspace{-1.5em}
Para resolver esta integral, la *fracción no tiene que tener singularidades en
el eje real*. 

Entonces, 
- si \( a > 0 \),  y \( \alpha_1, \cdots, \alpha_n \) son los polos en el *eje imaginario POSITIVO*, entonces
\[ \int _{- \infty}^{+ \infty} \frac{P(x)}{Q(x)} \; \text{d} x  = 2\pi i \sum
_{i=1}^{n} \text{Res} \left( \frac{P(z)}{Q(z)}e^{iaz}, \alpha_i \right)  \]

- si \( a < 0 \),  y \( \beta_1, \cdots, \beta_n \) son los polos en el *eje imaginario NEGATIVO*, entonces
\[ \int _{- \infty}^{+ \infty} \frac{P(x)}{Q(x)} \; \text{d} x  = -2\pi i \sum
_{i=1}^{n} \text{Res} \left( \frac{P(z)}{Q(z)}e^{iaz}, \beta_i \right)  \]

** [Extra] \(V.P. \int _{- \infty}^{+ \infty} \frac{P(x)}{Q(x)} \; \text{d} x   \)
\vspace{-1.5em}

\( V P . \int_{-\infty}^{+\infty} f(x) \mathrm{d} x= \)
\vspace{-0.5em}
\(\lim _{\varepsilon \rightarrow 0}\left(\int_{-\infty}^{x_{1}-\varepsilon} f(x) \mathrm{d} x+\sum_{j=1}^{p-1} \int_{x_{j}+\varepsilon}^{x_{j+1}-\varepsilon} f(x) \mathrm{d} x+\int_{x_{p}+\varepsilon}^{+\infty} f(x) \mathrm{d} x\right) \)

En este tipo de integral  *ord(Q) \ge 2 + ord(P)* y *\( Q(x) \) tiene ceros simples
en el eje real*.

Entonces,

\( V . P . \int_{-\infty}^{+\infty} \frac{P(x)}{Q(x)} \mathrm{d} x=2 \pi i \sum_{j=1}^{q} \operatorname{Res}\left(\frac{P(z)}{Q(z)}, z_{j}\right)+\pi i \sum_{j=1}^{p} \operatorname{Res}\left(\frac{P(z)}{Q(z)}, x_{j}\right) \)

Donde \( z_j \) son los ceros de \( Q(z) \) en el semiplano superior, y \( x_j
\) son los ceros en el eje real.

** [Extra] \( \int _{a}^{b} \frac{P(x)}{Q(x)} \; \text{d} x   \)
   En este tipo de integral  *ord(Q) \ge 1 + ord(P)* y *\( Q(x) \neq 0 \)  en \( [a,b] \)*.

Entonces,
\[ \int_{a}^{b} \frac{P(x)}{Q(x)} \mathrm{d} x=\sum_{j=1}^{q}
\operatorname{Res}\left(\frac{P(z)}{Q(z)} \log \frac{z-b}{z-a}, z_{j}\right)\]


** [Extra] \( \int _{a}^{+ \infty} \frac{P(x)}{Q(x)} \; \text{d} x   \)
   En este tipo de integral  *ord(Q) \ge 2 + ord(P)* y *\( Q(x) \neq 0 \)  en \(
   [a, +\infty) \)*.

Entonces,
\[ \int_{a}^{+\infty} \frac{P(x)}{Q(x)} \mathrm{d} x=-\sum_{j=1}^{q}
\operatorname{Res}\left(\frac{P(z)}{Q(z)} \log (z-a), z_{j}\right) \]

Donde \( \log \) es el logaritmo complejo.



#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT

* Transformación conforme
\vspace{-1.5em}
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT

\defi{9.0} una *transformación de Möbius* es una transformación \( \phi:
\hat{\mathbb{C}} \rightarrow  \hat{\mathbb{C}} \) o \( \phi: \mathbb{S}
\rightarrow  \mathbb{S} \).
\[ w = \phi(z) = \frac{az + b}{cz + d} \]
Donde \( a,b,c,d \in \hat{\mathbb{C}} \) y \( ad - bc \neq 0 \).

\obs{9.1} Se tiene que \( \phi(\infty) = \frac{a}{c} \) y \( \phi ^{-1}(\infty)
= - \frac{d }{c} \)

\obs{9.2} Casos particulares
- Traslación: \( w = z+b \)
- Homotecia de centro el origen: \( w = az \)
- Giros alrededor del origen: \( w = az, |a| = 1 \)
- Inversión: \(w = \frac{1}{z}\)

\propo{9.3.1} Una transformación de Möbius transforma el semiplano superior \(
H^+ = \{ z \;|\; \text{Im }z > 0 \} \) en el círculo unidad \( D(0,1) = \{ z
\;|\; |z| < 1 \} \) sii es de la forma 
\[ w = e^{i\theta} \frac{z - \alpha}{z - \bar{\alpha}} \]
donde \( \alpha \in H^+ \) y \( \theta \in [0, 2\pi] \).

\propo{9.3.2} Las transformaciones de Möbius que transforman el círculo unidad
sobre sí mismo son aquellas de la forma 
\[ w = e^{i\theta} \frac{z-\alpha}{1- \bar{\alpha}z} \]
donde \( |\alpha| < 1 \) y \( \theta \in [0, 2\pi] \).
#+BEGIN_EXPORT latex
\dem{ Topológicamente, toda transformación de Möbius que transforme el círculo
unida sobre sí mismo habrá de transformar la circunferencia unidad \( C(0,1) \)
sobre sí misma.
Sea \( \alpha \in D(0,1) \) que se transforma en el origen, de modo que el inverso 
\( \frac{1}{\bar{\alpha}} \) se transforma en \( \infty \). Así, la transformación 
\( w = \frac{az + b}{cz + d } \) debe satisfacer \( \alpha = - \frac{b}{a} \), 
\( \frac{1}{\alpha} = - \frac{d }{c} \), luego 
\[ w = \frac{a(z-\alpha)}{c(c - \frac{1}{\hat{\alpha}}} = \frac{a \hat{\alpha}}{c}\frac{z - \alpha}{\hat{\alpha} - 1} \]
Como además la imagen de \( z = 1 \in C(0,1) \), \( w(1) \in C(0,1) \), entonces
\( |w(1)| = 1 \) y \( \left|  \frac{a \hat{\alpha}}{c}\frac{z - \alpha}{\hat{\alpha} - 1}  \right| = 
 \left|  \frac{a \hat{\alpha}}{c} \right| = 1 \),
lo que prueba la proposición.}
#+END_EXPORT

\tma{9.4.1 (Tma de Riemann de la transformación conforme)} Sea \( A \subset
\mathbb{C} \) simplemente conexa y distinta a \( \mathbb{C} \). Entonces 
existe una transformación conforme \( f: A \rightarrow  D(0,1) \) analítica 
y biyectiva en \( C(0,1) \). Además, si fijamos \( z_0 \in A \) podemos
construir \( f \) tal que \( f(z_0) = 0 \) y \( f'(z_0) > 0 \in \mathbb{R} \).
Además, \( f \) es única.
#+BEGIN_EXPORT latex
\dem{ La unicidad es consecuencia del Lema de Schwarz. En efecto supongamos que 
hubiera dos transformaciones conformes $f, g$ biyectivas $f, g: A \rightarrow D(0,1)$ con 
$f\left(z_{0}\right)=g\left(z_{0}\right)=0$ y $f^{\prime}\left(z_{0}\right)>0, g^{\prime}\left(z_{0}\right)>0$. Entonces podemos definir
$h: D(0,1) \rightarrow D(0,1)$ mediante $h(w)=g \circ f^{-1}(w)$, de tal forma que 
$h(0)=$ $g\left(f^{-1}(0)\right)=g\left(z_{0}\right)=0$, y por tanto por el Lema de Schwarz 
$|h(w)| \leq|w|$ para $w \in D$. El mismo argumento es aplicable a $h^{-1}=f \circ g^{-1}$, 
de tal forma que $\left|h^{-1}(\zeta)\right| \leq|\zeta|$ para $\zeta \in D$ con $\zeta=h(w)$. 
Concluimos que $|h(w)|=|w|$ para todo $w \in D$, pero xen este caso el 
Lema de Schwarz asegura que $h(w)=e^{i \theta} w$ para $w \in D$ y por tanto tomando 
$w=f(z), z \in A$ también $e^{i \theta} f(z)=$ $h(f(z))=g \circ f^{-1}(f(z))=g(z)$. 
De aquí se concluye $e^{i \theta} f^{\prime}\left(z_{0}\right)=g^{\prime}\left(z_{0}\right)$ y
puesto que $f^{\prime}\left(z_{0}\right), g^{\prime}\left(z_{0}\right)$ son ambos positivos, obtenemos que 
$e^{i \theta}=1$ y por tanto $f(z) \equiv g(z)$.  }
#+END_EXPORT


\tma{9.4.2 (Fórmula de Schwarz-Christoffel)} La transformación confrme del
semiplano superior \( H^+ = \{ z \;|\; \text{Im }z>0 \} \) sobre el polígono
\( P \) viene dada por 
\[ w = f(z) = a \left( \int _{z_0}^z (\theta - x_1)^{-\alpha_1} \cdots 
(\theta - x_n)^{-\alpha_n}  \; \text{d}\theta  \right)  + b \]
donde \( a,b \) son parámetros a determinar a partir de los datos del polígono,
la integración se realiza a lo largo de cualquier camino \( \gamma \in H^+ \)
comenzando en \( z_0 \in H^+ \). Los puntos \( x_1, \cdots, x_n \) pueden ser
elegidos arbitrariamente y se verifica que \( f(x_1) = w_1, \cdots, f(x_n) = w_n \).


#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT


