#+TITLE: \Huge\vspace{-1em}Variable compleja
#+DATE:
#+SETUPFILE: ../Plantillas/Plantilla.org
#+OPTIONS: toc:nil ;; Nos quitamos el Índice del medio
#+OPTIONS: num:nil
#+LATEX: \vspace{-8em}

* Los números complejos
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT

\defi{1.1} Un número complejo es una expresión \( a + bi \) donde 
\( a,b \in \mathbb{R} \) y \( i \) es la unidad imaginaria, fruto de resolver la
ecuación \( x^2 + 1 = 0 \) en \( \mathbb{R} \). Así, definimos \( i = \sqrt{-1}
\). Si \( z \in \mathbb{C} = a + bi \), \( a = \text{Re }z \) y \( b = \text{Im
}z \) son la parte *real* e *imaginaria* de \( z \).

\defi{1.2} La *suma* y *multiplicación* están definidas en los complejos así:
\[ \left(x_{1}+y_{1} i\right)+\left(x_{2}+y_{2}
i\right)=\left(x_{1}+x_{2}\right)+\left(y_{1}+y_{2}\right) i \]
$$
\left(x_{1}+y_{1} i\right)\left(x_{2}+y_{2} i\right)=\left(x_{1} x_{2}-y_{1} y_{2}\right)+\left(x_{1} y_{2}+x_{2} y_{1}\right) i
$$
Y con estas operaciones \( (\mathbb{C}, +, \cdot) \) es un cuerpo, con \(
0_{\mathbb{C}} = 0 + 0i \) y \( 1_\mathbb{C} = 1 + 0i \).

\defi{1.3} Dado un complejo \( z = x + yi \), llamamos *conjugado* de \( z \), \(
\oveline{z} \) a \( x - yi \).

\propo{1.3.1} Se verifica que \( \overline{z_{1}+z_{2}}=\overline{z_{1}}+\overline{z_{2}} \) 
y \( \overline{z_{1} z_{2}}=\overline{z_{1}} \cdot \overline{z_{2}} \).

\defi{1.4.1} Se denomina *módulo* de un complejo \( z = x + yi \), \( |z| \) a \(
\sqrt{x^2 + y^2} \). Se cumple que \( |z| = \sqrt{z\overline{z}} \). 
El módulo cumple que (1) \( |z| \ge 0 \), (2) \( |z| = 0 \iff z = 0 \),
(3) \( |z_1z_2| = |z_1||z_2| \) y (4) \( |z_1 + z_2| \le |z_1| + |z_2| \)

#+BEGIN_EXPORT latex
\dem{ (4) \( 
\left|z_{1}+z_{2}\right|^{2}=\left(z_{1}+z_{2}\right)(\overline{z_{1}+z_{2}})=\left(z_{1}+z_{2}\right
)(\overline{z_{1}}+\overline{z_{2}}) 
=z_{1} \overline{z_{1}}+z_{1} \overline{z_{2}}+z_{2} \overline{z_{1}}+z_{2} \overline{z_{2}} 
=z_{1} \overline{z_{1}}+z_{1} \overline{z_{2}}+\overline{z_{1} \overline{z_{2}}}+z_{2} \overline{z_{2}} 
=\left|z_{1}\right|^{2}+\left|z_{2}\right|^{2}+2 \operatorname{Re}\left(z_{1} \overline{z_{2}}\right) 
 \leq\left|z_{1}\right|^{2}+\left|z_{2}\right|^{2}+2\left|z_{1}\right|\left|z_{2}\right| 
=\left(\left|z_{1}\right|+\left|z_{2}\right|\right)^{2}
 \)  }
#+END_EXPORT

\defi{1.5} Dado un \( z = a + bi \), aplicando \( u = p + iq = z/|z| \),
entonces \( |u| = 1 = p^2 + q^2 \). El ángulo tal que \( p = \cos \alpha, q =
\sin \alpha \) se denomina *argumento*, \( \arg z \).  Así, \( z \) puede representarse como \( z
= |z|(\cos  \alpha  + i \sin \alpha ) \). Esta forma es la *forma polar*, y
también se representa como \( z = |z|e^{i\alpha} \).x 

El argumento cumple que (1) \( \arg \overline{z} = - \arg z \) y (2) \( \arg
z_1z_2 = \arg z_1 + \arg z_2 \).

\defi{1.7 / 1.8} El espacio topológico \( (\mathbb{C}, \delta_E) \) con distancia
euclídea no es compacto. Sin embargo, si tomamos \( \hat{\mathbb{C}} =
\mathbb{C} \cup \{ \infty \} \) entonces sí es compacto, y lo denominamos *plano
complejo ampliado*. La *esfera de Riemann*, \( \mathbb{S} \), es la representación del conjunto \(
\hat{\mathbb{C}} \) en \( \mathbb{R}^3_{(\xi, \eta, \zeta)} \) en una esfera con
centro \( (0, 0, 1/2) \) con ecuación \( \xi^{2}+\eta^{2}+\zeta^{2}-\zeta=0 \).
#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=5cm]{imagenes/esfera.png}
\end{figure}
#+END_EXPORT
La relación entre la esfera y el plano es 
\[ \xi=\frac{x}{1+x^{2}+y^{2}}, \eta=\frac{y}{1+x^{2}+y^{2}}, \zeta=\frac{x^{2}+y^{2}}{1+x^{2}+y^{2}} \]
La *distancia cordal* entre dos puntos \( z_1,z_2 \) es la distancia euclídea 
entre los puntos \( P_1,P_2 \) de la esfera de la esfera de Riemman.

\( \delta(z_1,z_2) =
 \sqrt{\left(\xi_{1}-\xi_{2}\right)^{2}+\left(\eta_{1}-\eta_{2}\right)^{2}+\left(\zeta_{1}-\zeta_{2}\right)^{2}}
 = \frac{\sqrt{\left(x_{1}-x_{2}\right)^{2}+\left(y_{1}-y_{2}\right)^{2}}}{
\sqrt{\left(1+x_{1}^{2}+y_{1}^{2}\right)\left(1+x_{2}^{2}+y_{2}^{2}\right)}} \)

Para un punto en el infinito, la distancia es \( \delta(z, \infty)=\frac{1}{\sqrt{1+x^{2}+y^{2}}} \)

#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT




* Funciones complejas
#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT
\defi{2.0} Una función puede ser de tipo \( f: \mathbb{R} \rightarrow
\mathbb{C} \) (f. compleja de var. real) o 
\( f: \mathbb{C} \rightarrow  \mathbb{C} \) (f. compleja de var. compleja).

\defi{2.1.1} \( f = f(z)\) es *continua* en \( z_0 \in \mathbb{C} \) si para todo \(
\epsilon > 0 \) existe \( \delta > 0 \) tal que si \( |z - z_0| < \delta \)
entonces \( |f(z) - f(z_0)| < \epsilon \). \( f \) es *uniformemente continua* en
\( B \subset \mathbb{C} \) si
dado \( \epsilon > 0 \) existe \( \delta > 0 \) tal que para todo \( z_0 \in B
\) y para todo \( z \) tal que \( |z-z_0| < \delta \) entonces \( |f(z) -
f(z_0)| < \epsilon \).  Si \( f \) es uniformemente continua es continua, pero
no siempre a la inversa.

\tma{2.1.1} Si \( f_1(z), f_2(z) \) están definidas en \( A \subset \mathbb{C}
\), \( A \) abierto, y son continuas en \( z_0 \in A \), f_1 + f_2 y f_1/f_2 son
continuas en \( z_0 \). Así, los polinomios complejos son continuos.

\defi{2.1.2} Una función \( f(z) \) en \( A \subset \mathb{S} \) es continua en
\( z_0 \) si para todo \( \epsilon > 0 \)
 existe \( \eta > 0 \) tal que para todo \( z \in A \) donde \( \delta(z, z_0) <
\eta \) entonces \( \delta(f(z_0), f(z)) < \epsilon \).

\defi{2.2.1, 2.2.2} Una función \( f(z) \) es *derivable* en \( z_0 \) si existe el
límite \( \lim_{z \to z_0} \frac{f(z) - f(z_0)}{z-z_0} \) y es finito.
Si \( z_0 = \infty \), consideramos \( g(z) = f(1/z) \) y \( f \) es derivable
en \( \infty \) si \( g \) es derivable en \( z=0 \).
Una función \( f:A \subset \mathbb{C} \rightarrow  \mathbb{C} \) derivable en todo
\( A \) se llama función *holomorfa* o *analítica.*

\propo{2.3.2} Si \( f \) es derivable en un punto, también es continua en ese
punto.

\propo{2.3.4 (Regla de la cadena)} Sean \( g:A \rightarrow  \mathbb{C} \) y \(
f: B \rightarrow \mathbb{C} \) tales que \( g(A) \subset B \). Si \( g \) es
derivable en \( z_0 \) y \( f\) es derivable en \( g(z_0)  \) entonces \( f
\circ g'(z_0) = f'(g(z_0))g'(z_0) \).

\defi{2.4.1} Una función \( f: A \rightarrow  \mathbb{C} \) es conforme en \(
z_0 \) si existe exsite \( \theta \in [0, 2\pi] \) tal que cualquier curva \(
\gamma(t) \) diferenciable en \( t_0 \), \( \gamma(t_0) = z_0 \) y \(
\gamma'(t_0) \neq 0 \) se transforma por \( f \) en una curva \( \sigma(t) =
f(\gamma(t)) \) diferenciable en \( t_0 \) tal que \( \sigma'(t_0) =
\gamma'(t_0) + \theta \). Si \( \alpha \) es el ángulo en el punto de cruce \(
z_0 \) entre \( \gamma_1, \gamma_2 \), entonces el ángulo de \( f(\gamma_1),
f(\gamma_2) \) es \( \alpha \).  

\tma{2.4.1} Si \( f \) es derivable en \( z_0 \) y \( f'(z_0) \neq 0 \) entonces
\( f \) es conforme en \( z_0 \) y \( \theta = \arg f'(z_0) \). Si \( f \) es
holomorfa, es conforme.
 #+BEGIN_EXPORT latex
\dem{ Por la regla de la cadena, \( \sigma'(t_0) = f'(\gamma(t_0))\cdot \gamma'(t_0) \)  y \( \arg  \sigma'(t_0)
 = \arg f'(\gamma(t_0))+\arg  \gamma'(t_0) \) }
#+END_EXPORT

\defi{2.5.1} Una función de variable compleja puede transformarse a una función
\( f: \mathbb{R}^2 \rightarrow  \mathbb{R}^2 \): \( f(x,y) = (u(x,y) + v(x,y)) =
u(x,y) + v(x,y)i \)

\tma{2.5.1 (Ecuaciones de Cauchy-Riemman) } Sea \( f \). \( f'(z_0) \) existe sii \( f \) es diferenciable como
función de dos variables y las funciones \( u(x,y), v(x,y) \) satisfacen
\vspace{-1em} \[
\frac{\partial u}{\partial x} = \frac{\partial v}{\partial y}, 
\frac{\partial u}{\partial y} = - \frac{\partial v}{\partial x} \]
#+BEGIN_EXPORT latex
\dem{ Suponemos \( f \) derivable en \( z_0 \) complejo, con derivada \( \lambda = f'(z_0) \). 
Si tomamos la aplicación lineal \( l_c : \mathbb{C} \rightarrow  \mathbb{C}; \eta \rightarrow \lambda\eta \).
Entonces \( \lim_{\eta \to 0} \left|\frac{f(z_0 + \eta) - f(z_0)}{\eta} - \lambda  \right| = \lim_{\eta \to 0} 
\frac{|f(z_0 + \eta) - f(z_0) - l_c(\eta)|}{|\eta|} =  0 \). Escribiendo \( f(z_0) \) y 
\( l_c(\eta) \) como componentes reales: (1) \( f(z_0) = u(x_0, y_0) + v(x_0,y_0)i = 
(u(x_0, y_0), v(x_0, y_0)) \) su jacobiano es \( D= \begin{bmatrix}
\frac{\partial u}{\partial x} &  \frac{\partial u}{\partial y} \\ 
\frac{\partial v}{\partial x} &  \frac{\partial v}{\partial y} \\ 
\end{bmatrix}  \) y (2)
\(l_c(\eta) = \lambda\eta = (\lambda_1 + \lambda_2i)(\eta_1 + \eta_2i) = (\lambda_1\eta_1 - \lambda_2\eta_2, \lambda_1\eta_2 + \lambda_2\eta_1)  \), 
que como aplicación lineal \( \mathbb{R}^2 \rightarrow  \mathbb{R}^2 \) 
es \( A= \begin{bmatrix}
\lambda_1 &  -\lambda_2 \\ 
\lambda_2 &  \lambda_1 \\ 
\end{bmatrix}  \). Como el jacobiano la derivada de \( f \) en los reales, y \( A \) es también la diferencial de 
\( f \) en \( z_0 \), \( D = A \), y se dan las ecuaciones. }
#+END_EXPORT

\tma{2.6.1 (Teorema de la función inversa)} Sea \( f \) analítica con derivada
continua en \( A \). Sea \( z_0 \in A\) tal que \( f'(z_0) \neq 0  \). Entonces,
existen \( U, V \) abiertos tal que \( z_0 \in U \), \( f(z_0) \in V \) y \( f:
U \rightarrow  V \) es biyectiva. Además, \(f^{-1}\) es analítica en \( V \) y para
todo \( z \in U \), \( (f^{-1})'(f(z)) = \frac{1}{f'(z)} \).



#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT

* Series de potencias. Funciones elementales

#+BEGIN_EXPORT latex
\begin{multicols*}{2}
#+END_EXPORT

\defi{3.0.1} Una *sucesión* de complejos es una aplicación \( \mathbb{N}
\rightarrow  \mathbb{C} \) tal que para cada \( n \in \mathbb{N} \) se le
corresponde \( a_n \in \mathbb{C} \). 

\defi{3.0.2} Una *serie* es una sucesión de complejos \( \{A_n\}_{n \in \mathbb{N} }
\) tal que \( A_n = \sum _{i=0}^{n} a_i\).

\defi{3.0.3} Una sucesión es de *Cauchy* o *fundamental* si dado \( \epsilon > 0 \)
existe \( n_0 \in \mathbb{N} \) tal que para todo \( n_1, n_2 \ge n_0 \), se
tiene que \(|a_{n_1} - a_{n_2}| < \epsilon  \).

\defi{3.0.4} Se dice que \( \{a_n\}_{n \in \mathbb{N}} \) es *convergente* a \( a \)
si dado \( \epsilon > 0 \) existe \( n_0 \in \mathbb{N} \) tal que para todo \(
n \ge n_0 \) se tiene \( |a_n-a| < \epsilon \), y diremos \( \lim_{n \to \infty}
a_n=a\).  Asimismo, \( A_n \) es convergente a \( A \) si \( \lim_{n \to \infty}
A_n = A\).

\defi{3.0.5} Una serie \( A_n \) es absolutamente convergente si la serie \(
\sum |a_n|  \) es convergente.

\tma{3.1.1 (Criterio de la raíz) } Dado \( \sum _{i=1}^{\infty} a_i \), sea \(
\lambda = \lim_{n \to \infty} \text{sup} \sqrt[\leftroot{1}\uproot{1}n]{|a_n|}
\). Si \( \lambda < 1 \) la serie converge y si \( \lambda > 1 \) diverge.

\tma{3.1.2 (Criterio del cociente)} Dado  
\( \sum _{i=1}^{\infty} a_i \) sea \( \beta = \lim_{n \to \infty}
\frac{|a_n|}{|a_{n-1}|} \), si \( \beta < 1 \) la serie converge, y si \( \beta >
1 \) diverge.

\defi{3.2.0} Una *sucesión* *de variable compleja* es una aplicación de tal manera
que a cada \( n \in \mathbb{N} \) le corresponde una función \( f_n: A
\rightarrow  \mathbb{C} \). Representamos la sucesión por \( \{ f_n \}_{n \in
\mathbb{N}} \). Asimismo, una *serie de funciones de variable compleja* es el
resultado de sumar dichas funciones: \( F_n(z) = \sum _{i=1}^{n}f_i\).

\defi{3.2.1} Una sucesión \( \{ f_n \}_{n \in N}  \) converge en \( z_0 \in A \) cuando
converge la sucesión numérica \( \{ f_n(z_0) \}_{n \in \mathbb{N}} \). Diremos
que \( \{ f_n \}_{n \in \mathbb{N}} \) *converge puntualmente* cuando converge
para todo \( z \in A \).

\defi{3.2.2} La serie \( f_0 + \cdots + f_n + \cdots \) converge en un punto \(
z_0 \in A \), \( A \) abierto en \( \mathbb{C} \) si la sucesión \( \{ F_n(z_0) \}_{n
\in \mathbb{N}} \) con \( F_n = f_0 + \cdots + f_n \)
converge. La serie converge puntualmente en \( A  \) si \( \{ F_n \}_{n \in
\mathbb{N}} \) converge puntualmente en \( A \).

\defi{3.2.3} La sucesión de funciones \( \{ f_n \}_{n \in N} \) converge
uniformemente a \( f \) si para todo \( \epsilon > 0 \) existe \( n_0 \in
\mathbb{N} \) tal que \( |f_n(z) - f(z)| < \epsilon \) para todo \( z \in A, n
\ge n_0 \). 

\defi{3.2.4} La serie \( \sum _{n=1}^{\infty} f_n(z) \) converge uniformemente
en \( A \) si la sucesión \( \{ F_n \}_{n \in N} \) converge uniformemente en \(
A \).

\tma{3.2.1 Criterio de la mayorante de Weierstrass)} Una condición suficiente
para que \( \sum _{n=1}^{\infty} f_n \) converja uniformemente en \( A \subset
\mathbb{C} \) es que exista una serie \( \sum _{n=1}^{\infty} a_n \) convergente
tal que \( |f_n(z)| \le a_n \) para todo \( z \) y \( n \in \mathbb{N} \).
En tal caso, \( \sum _{n=1}^{\infty} a_n \) es una mayorante de \( \sum
_{n=1}^{\infty} f_n \). 

\defi{3.3.0} Una *serie de potencias* es una serie de la forma \( \sum
_{n=1}^{\infty} a_n(z - z_0)^n \), con \( z_0, a_n \in \mathbb{C} \) para todo
\( n \). Los \( a_n \) se llaman *coeficientes* de la serie.
Si \( z_0=0 \), es decir, \( \sum _{n=1}^{\infty} a_nz^n \) decimos que la serie
está *centrada en el origen*.

\defi{3.3.1 (Teorema de Cauchy-Hadamard)} Dada la serie \( \sum _{n=1}^{\infty}
a_n(z - z_0)^n \) considerando  \(
\lambda = \lim_{n \to \infty} \text{sup} \sqrt[\leftroot{1}\uproot{1}n]{|a_n|}
\); si llamamos \( R = \frac{1}{\lambda} \), tenemos:
- La serie converge absolutamente en el interior del círculo \( D_R = \{z| |z-z_0| < R \} \) y diverge en el exterior \( \overline{D_R} = \{ z| |z-z_0|> R \} \) 
- La convergencia es uniforme en todo circulo de radio \( 0 \le r < R \) 
\( R \) se llama *radio de convergencia* de la serie. 


\tma{3.3.2} La función definida por la suma de serie de potencias en su círculo
de convergencia es derivable en todo punto de dicho círculo:
\[ \frac{\text{d}}{\text{d}z} \left( \sum _{n=0}^{\infty}a_n(z-z_0)^n \right) = 
\sum _{n=0}^{\infty}na_n(z-z_0)^{n-1} \].

\defi{3.4.1} La función exponencial compleja es \[ e^z = \sum_{n=0}^{\infty}
\frac{z^n}{n!} \].
Su radio de convergencia es \( R = \infty \). Cumple también que \( e^{z_1+z_2}
 = e^{z_1}e^{z_2} \).
El exponente puede reescribirse como \( e^z = e^{x+yi} = e^xe^{iy} = e^x(\cos
y + i \sin y) \)

\defi{3.4.2} La función logaritmo se obtiene desde la exponencial. Escribiendo
\( z = r e^{i\theta} \) tenemos que \( \log z  = \log|r| + i\theta = \log|r| + i
\arg(z) \). Como \( \arg(z) = \theta + 2\pi k \), el logaritmo principal es \(
\theta \in [0, 2\pi] = \text{Arg } z \).

\defi{3.4.3} Las funciones seno y coseno se definen a través de sus series de
potencias con \( R = \infty \):
\[ \sin(z) = \sum _{n=0}^{\infty} (-1)^n \frac{z^{2n+1}}{(2n+1)!}\;,\; 
\cos(z) = \sum _{n=0}^{\infty}(-1)^n \frac{z^{2n}}{(2n)!} \]
La derivación es como con los números reales, y las identidades de Euler son
idénticas:
\[ \cos(z) = \frac{e^{iz} + e^{-iz}}{2} \;,\; \sin(z) = \frac{e^{iz} -
e^{-iz}}{2i} \]
\[ \sinh(z) = \frac{e^z - e^{-z}}{2}\;,\; \cosh(z) = \frac{e^z + e^{-z}}{2} \]

\defi{3.4.4} La función potencial con exponente complejo, \( z^\zeta, \zeta \in
\mathbb{C} \) es \( z^{\zeta} = e^{\zeta \log z} \)

\defi{3.5.1 (Funciones multiformes)}  Una función \( f \) es multiforme cuando
\( w = f(z) \) puede tomar diferentes valores para el mismo \( z \). Por
ejemplo, para \( f = \sqrt{z} \), \( f(2i) = 1+i \) y \( f(2i) = -1-i \). 
Esto se debe a que \( z^{1/2} = e^{\frac{1}{2} \log{z}} =
e^{\frac{1}{2}(\log{|z| + i \arg(z))}} = |z|^{\frac{1}{2}}e^{i \frac{\text{Arg
}z + 2k\pi}{2}}, k = 0,1\).

Observamos que como \( k \) puede tomar dos valores, entonces la función tiene
dos ramas, es decir, \( w_1 = \sqrt{r}e^{i \frac{\theta}{2}}\;,\;w_2 =
-\sqrt{r}e^{-i \frac{\theta}{2}} \).
Por tanto, para completar un ciclo en \( w \) necesitamos completar dos ciclos
en \( z \) (uno por rama). Esto genera una *superficie de Riemann* como la
siguiente figura:

#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=9cm]{imagenes/riemann_sqrt.png}
\end{figure}
#+END_EXPORT

En este caso los ejes \( X \) e \( Y \) representan el plano complejo de \( z
\). El eje \( Z \) representa la parte real de \( f(z) \), y el color representa
la imaginaria. El punto de corte del plano es el caso \( \sqrt{-a}, a \in
\mathbb{R}  = 0 + i \sqrt{a}\). Sin embargo, el corte es un artefacto de la
visualización tridimensional de 4 dimensiones.

Debajo se muestra el ejemplo de \( f = \log{z} \), donde el eje \( X \)
representa el argumento, y el color representa la parte real. 

#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=8cm]{imagenes/riemann_log.png}
\end{figure}
#+END_EXPORT

Vemos que el el plano "cae" de nivel en cada vuelta. Esto es el equivalente a
cada rama del logaritmo.


#+BEGIN_EXPORT latex
\end{multicols*}
\pagebreak
#+END_EXPORT
