#+TITLE: \Huge\vspace{-1em}Estructuras algebráicas
#+DATE:
#+SETUPFILE: ../Plantillas/Plantilla.org
#+OPTIONS: toc:nil ;; Nos quitamos el Índice del medio
#+LATEX: \vspace{-8em}
#+STARTUP: latexpreview

* Grupos
\defi{1.1} Un grupo es un conjunto no vacío \( G \) en el que se define una 
operación binaria \( G \times G \rightarrow G\;;\; (a,b) \mapsto ab \) que cumple (1) *asociatividad*
(\( (ab)c = a(bc) \)), (2) *existencia de elemento neutro* \( u \in G\;;\;ua=a=au \)
y (3) *existencia de elemento inverso* \( a,x \in G \;;\; ax = u = xa \). Tanto \( u
\) como \( a \) 
son únicos. Para la suma \( u = 0, a=-x \) y para el producto \(
u = 1, a = x^{-1} \).

Otras propiedades inmediatas de los grupos son (1) *simplificación*: \( ab=ac \iff b=c
\); \( ba = ca \iff b=c
\); (2) *asociatividad generalizada*: \( (a_1 \cdots a_k)(a_{k+1} \cdots a_n ) =
(a_1 \cdots a_l)(a_{l+1} \cdots a_n) \) 
, (3) *inverso de un producto*: \( (a_1 \cdots a_n)^{-1}  = a_n^{-1} \cdots
a_1^{-1} \).

\defi{1.2} Un *grupo simétrico* \( S_n \) es el conjunto de biyecciones de un
conjunto \( X \) con \( n \) elementos. Se cumple que \( \text{card}(S_n) = n!
\). Otros ejemplos de 
grupos son \( GL_n(\mathbb{R}) \), el grupo de matrices no
singulares para la operación producto; o \( D_n \) es el conjunto de biyecciones
que conserva la distancia en un polígono de \( n \) lados. 

\defi{1.3} Un grupo es *abeliano* si \( ab = ba\;\; \forall a,b \in G \).
Todo grupo con dos elementos es abeliano, pues \( aa = aa; uu=uu; ua=a=au \);
pero para \( n \ge 3 \), \( S_n \) no puede ser abeliano. \( GL_n; n \ge 2 \),
ni \( D_n; n \ge 3 \) son abelianos.

\propo{1.4} (1) Si \( x^2 = 1 \; \forall x \in G \), entonces \( G \) es
abeliano; (2) si \( (ab)^2=a^2b^2 \) entonces \( G \) es abeliano.

\dem{(1) Para cada \( x,\; x \cdot x = 1 \iff x = x^{-1}\), luego si \( a,b \in G \) 
entonces \( a = a^{-1}; b=b^{-1} \) y si \( c = ab\) entonces 
\( ab = c =c^{-1} = (ab)^{-1} = b^{-1}a^{-1} = ba \). (2) Dados \( a,b \in G \), 
se tiene que \( a(ba)b = (ab)^2 = a^2b^2 = a(ab)b \) y, por simplificación,
 \( ab = ba \).} 

\defi{1.5} Si \( G,G' \) son dos grupos con operaciones
\( G \times G \rightarrow G: (a,b) \mapsto ab \qquad G' \times G' \rightarrow G': (a', b') \mapsto a'b'
\)
 el *producto cartesiano* \( G'' = G \times G''
 \) es un grupo con operación 
\( G'' \times G'' \rightarrow G'': ((a, a'), (b, b')) = (ab, a'b')
\). La asociatividad se mantiene, y se ve que \( 1_{G''} = (1_G, 1_{G'}) \).
Además, si \( G, G' \) son abelianos, \( G'' \) también lo es.


